### PR TITLE
Check pad deltas - Ready for Review / Merge @muxator

### PR DESCRIPTION
**Pull request by JohnMcLear**
As per https://gist.github.com/marcelklehr/a78d293571e7f06e3cf9

Requested in https://github.com/ether/etherpad-lite/issues/2107

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Mheh I didn't rebase but I'm pretty sure the showChat stuff is good to merge so all good to just use this.

**Comment by muxator** [comment]
So this PR just need to add `bin/checkPadDeltas.js`, right?

**Comment by muxator** [comment]
So I went ahead and downloaded [Marcel's original version](https://gist.github.com/marcelklehr/a78d293571e7f06e3cf9) from the url you mentioned, and then put yours on top.

This results in the following diff, which is difficult to understand: https://github.com/ether/etherpad-lite/pull/3717/commits/0d3e825d996c6f4b9892a3bd1b93c17f2a0b6cf9

Could you explain it? From the initial comment i thought it was similar or equal to the file you linked, but there are many differences.

Any pointers? Thanks

**Comment by JohnMcLear** [comment]
Afaik I used async / await that's pretty much all, I think I had to do some polish because something was broken, remember stuff like pad.getPadAuthors was b0rked in 1.7 or so

**Comment by muxator** [comment]
Pulled in, thanks.

**Pull request merged**
