### PR TITLE
Feat/frontend vitest

### PR DESCRIPTION
**Pull request by SamTV12345**

### CODE REVIEW

**Comment by SamTV12345** [comment]
Hi @AugustinMauroy maybe you have an idea why the vitest tests don't work. I ported settings.spec.ts to the new directory for tests but it is complaining about not finding a module. Do you know why?

**Comment by AugustinMauroy** [comment]
Heyyy !
how dit you call test, I mean which command did you use ?

**Comment by SamTV12345** [comment]
> Heyyy !
> 
> how dit you call test, I mean which command did you use ?

Hey :). Thanks for helping me out. It's npx vitest --config vitest.config.ts

**Comment by AugustinMauroy** [comment]
Ok I got it !
it's because vitest cannot make esm and cjs in same time so when you still have require you I'll need to use import

**Comment by SamTV12345** [comment]
> Ok I got it ! it's because vitest cannot make esm and cjs in same time so when you still have require you I'll need to use import

Thanks. I'll check if import works :).

**Pull request merged**
