### PR TITLE
WIP fix(settings): Reloading after removing settings keys

### PR DESCRIPTION
**Pull request by orblivion**
Addressing issue in #4217 

# The Problem

If you have a field in settings with a default value (hardcoded in `src/node/utils/Settings.js`), you can override it in a custom setting in `settings.json`. The settings admin (`/admin/settings`) lets you edit that custom setting, and click "save" and "reload" and it takes effect as expected. However if in the settings admin you _remove_ that setting, it doesn't go back to the default value; the value just stays the same. However if you do a hard restart of the server, the value does go back to the default.

# The Explanation

When you call `reloadSettings()` from the settings.json editor admin, it will take the your new settings and merge it, more or less, with the _currently loaded_ settings, not the _default_ settings. When you remove a key and reload within the settings admin, it overrides that now-missing key with the existing value, which is the custom value you had there before you removed it. If you do a hard reset, the previous custom value is flushed from memory, and it goes through the usual process of loading the default before loading any custom values.

This phenomenon happens at different levels of the `settings.json` object hierarchy, but I'm not sure if it happens at all of them, because of the merging method used. This may also depend on whether it's a plugin setting or not.

# The Proposed Fix

For my fix, I make a new function called `setDefaults()` which overwrites all of the settings with the defaults. I call it within `reloadSettings()` before `storeSettings(settings)` and `storeSettings(credentials)`. This also involves putting the defaults into its own easily identified object.

Assuming this is the desired path (per core developers' opinion(s)), I'll see if I can write some tests, and then clean up some confusing comments.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@rhansen are you happy with this?

**Comment by rhansen** [comment]
I think this is better than what we have now, so it's worth merging after tests are added.

Some easy (I think) ways to improve this PR, if you feel up to it:
* Do a deep copy of `defaultSettings` instead of a shallow copy.
* Re-run the `loadSettings` hook on reload.

If you want to go the extra mile, you could use [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to track dynamic modifications so that they can be reapplied after a reload. `Proxy` could also be used to provide an updatable view onto the current settings, so that a module that does `const foo = settings.foo;` automatically sees the new `foo` settings object.

**Comment by JohnMcLear** [comment]
@orblivion can you get the tests in and conflicts resolved please? :)  Thanks!

**Comment by JohnMcLear** [comment]
Still waiting on @orblivion for testing?

**Comment by JohnMcLear** [comment]
@rhansen I wonder if your latest round of work makes this PR defunct?

**Comment by rhansen** [comment]
> @rhansen I wonder if your latest round of work makes this PR defunct?

No, this PR is still valid.

**Comment by orblivion** [comment]
Got probably most of the tests. Tried to catch lots of scenarios. Have a few more. Still need to consider other comments here.

**Comment by JohnMcLear** [comment]
Bump @orblivion  :)

**Pull request closed without merging**
