### PR TITLE
Migrate Socket.IO from Version 2 to Version 3 🚀

### PR DESCRIPTION
**Pull request by HMarzban**
Upgraded the Socket.IO library from version 2 to version 3. 
This PR is a continuation of PR #4916. 
@SamTV12345 🧑‍💻

### CODE REVIEW

**Comment by SamTV12345** [comment]
That looks awesome. I'll review and test tomorrow. If all looks good I'll merge this. Would you be interested in also upgrading to v4 after that?

**Comment by HMarzban** [comment]
Great, thanks! If it all goes smoothly, I'm up for upgrading to v4 next.

**Comment by SamTV12345** [comment]
@HMarzban  could you reset the test timeout in the package.json? I think that is why the load tests are failing.

**Comment by HMarzban** [comment]
Encountered another failure. I've reviewed the etherpad-load-test, and it turns out it utilizes the etherpad-cli-client. This CLI depends on socket.io-client v2, which is the root of the problem and needs upgrading. 

However, on a positive note, the backend tests passed successfully. 

I also manually tested all functionalities of the client, and everything appeared to be functioning correctly.

**Comment by HMarzban** [comment]
Upgrading from v3 to v4 requires more extensive refactoring, but only on the backend side. 
As far as I'm aware, the client-side SDK (v3) is compatible with the v4 server-side. 
Therefore, I recommend we first thoroughly test and address any potential issues with v3. 

Once that's done, I can start working on upgrading the socket to v4.

**Comment by HMarzban** [comment]
> When I start Etherpad I get a bad request {"code":0,"message":"Transport unknown"}

In the new version of socket.io, the socket protocols such as `["xhr-polling", "jsonp-polling", "htmlfile"]` are no longer available. 

Therefore, you will need to update them to `["websocket", "polling"]`.

change the settings:
```js
---
"socketTransportProtocols" : ["websocket", "polling"],
---
```

**Comment by SamTV12345** [comment]
> Upgrading from v3 to v4 requires more extensive refactoring, but only on the backend side. As far as I'm aware, the client-side SDK (v3) is compatible with the v4 server-side. Therefore, I recommend we first thoroughly test and address any potential issues with v3.
> 
> Once that's done, I can start working on upgrading the socket to v4.

Good idea. I'm currently fighting over on etherpad-cli-client. I guess this is because the loadtests fail. Thanks that did fix the issue. Maybe I can just update the settings when the user starts Etherpad. Otherwise we will get a lot of complaints that their Etherpad instances broke.

**Comment by SamTV12345** [comment]
@HMarzban Do you have an idea how to fix the pipelines https://github.com/ether/etherpad-cli-client?

**Comment by HMarzban** [comment]
Sure, I'm quite busy at the moment, but I believe you can handle this. 
If you need a detailed review, though, I'm here to help on Friday. 

Just give these steps a try, and you should be able to fix it yourself!

In this [line](https://github.com/ether/etherpad-cli-client/blob/17d2c0a6527ee7f808aaf32fa6ba7f73342e5e57/lib/index.js#L47), the `connect` should be changed to `connection`:

Then, in this [line](https://github.com/ether/etherpad-cli-client/blob/17d2c0a6527ee7f808aaf32fa6ba7f73342e5e57/lib/index.js#L212):
```js
        socket.json.send({
          type: 'COLLABROOM',
          component: 'pad',
          data: JSON.parse(JSON.stringify(padState.inFlight)),
        });
```
TO:
```js
        socket.emit('message', {
          type: 'COLLABROOM',
          component: 'pad',
          data: JSON.parse(JSON.stringify(padState.inFlight)),
        });
```

Also, this [line](https://github.com/ether/etherpad-cli-client/blob/17d2c0a6527ee7f808aaf32fa6ba7f73342e5e57/lib/index.js#L63C7-L63C23) should be changed to:
`socket.emit('message', msg);`

**Comment by SamTV12345** [comment]
> Sure, I'm quite busy at the moment, but I believe you can handle this. If you need a detailed review, though, I'm here to help on Friday.
> 
> Just give these steps a try, and you should be able to fix it yourself!
> 
> Then, in this [line](https://github.com/ether/etherpad-cli-client/blob/17d2c0a6527ee7f808aaf32fa6ba7f73342e5e57/lib/index.js#L212):
> 
> ```js
>   socket.json.send({
>     type: 'COLLABROOM',
>     component: 'pad',
>     data: JSON.parse(JSON.stringify(padState.inFlight)),
>   });
> ```
> 
> TO:
> 
> ```js
>   socket.emit('message', {
>     type: 'COLLABROOM',
>     component: 'pad',
>     data: JSON.parse(JSON.stringify(padState.inFlight)),
>   });
> ```
> 
> Also, this [line](https://github.com/ether/etherpad-cli-client/blob/17d2c0a6527ee7f808aaf32fa6ba7f73342e5e57/lib/index.js#L63C7-L63C23) should be changed to: `socket.emit('message', msg);`

I am unfortunately not really familiar with the pipelines. Maybe you know what is done in there and can port that over to pnpm.

**Comment by SamTV12345** [comment]
Awesome. I had to go through a lot of hoops but eventually I managed to migrate the load test and the cli to socket.io v3. Thanks for the help with this upgrade and I am hyped for the upgrade to the latest socket io version

**Comment by HMarzban** [comment]
Great, let's rock and roll. 😃

**Pull request merged**
