### PR TITLE
deps: formdidable 3.1.3 - requires node 13 or hack.  

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
```
  1) D:\a\etherpad-lite\etherpad-lite\src\tests\backend\specs\api\api.js
       can obtain API version:
     Error: expected 200 "OK", got 404 "Not Found"
      at Context.<anonymous> (tests\backend\specs\api\api.js:37:10)
      at processImmediate (internal/timers.js:464:21)
```

**Comment by JohnMcLear** [comment]
```
[2023-06-24 09:50:35.477] [ERROR] console - Failed to load hook function "/home/jose/etherpad-lite/node_modules/ep_etherpad-lite/node/hooks/express/openapi:expressPreSession" for plugin "ep_etherpad-lite" part "openapi" hook set "hooks" hook "expressPreSession": Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jose/etherpad-lite/src/node_modules/formidable/src/index.js
require() of ES modules is not supported.
```

**Comment by JohnMcLear** [comment]
```
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/jose/etherpad-lite/src/node_modules/formidable/package.json.
```

**Comment by JohnMcLear** [comment]
We can address this when we bump to node13 as requirement.

12 is not enough

**Comment by SamTV12345** [comment]
Don't we have Node 14 in your package.json as a requirement?

**Comment by JohnMcLear** [comment]
> Don't we have Node 14 in your package.json as a requirement?

I think so ergo I must be incorrect.

**Pull request closed without merging**
