### PR TITLE
Feature #2567 Added workaround to enable contentcollector to write key-v...

### PR DESCRIPTION
**Pull request by tm-linkwerk**
...alue attributes

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Should we get some docs in with this PR so that people know to use it?

**Comment by tm-linkwerk** [comment]
Where should those docs go to?

**Comment by JohnMcLear** [comment]
Needs to land here: http://etherpad.org/doc/v1.5.0/#index_collectcontentpre
You would modify: https://github.com/ether/etherpad-lite/blob/develop/doc/api/hooks_client-side.md#collectcontentpre

I guess?

**Comment by JohnMcLear** [comment]
All tests pass for me :)  Good job!

**Pull request merged**
