### PR TITLE
migrateDirtyDBtoRealDB: fix the script, which did not work

### PR DESCRIPTION
**Pull request by JohnMcLear**
Fixes https://github.com/ether/etherpad-lite/issues/2214

node dirty returns wrong length on ``.load``

I fix by doing forEach twice, once to get the length then again to do the process.  Then I terminate on end of process..

### CODE REVIEW

**Comment by muxator** [comment]
This was not scheduled for **1.8.4**. However, it is out of core, and if it is useful we can include it anyway.

@JohnMcLear, could you briefly describe what is the problem you are fixing so I can annotate the change and we can merge it right away?

**Comment by JohnMcLear** [comment]
The syntax used for dirty didn't work.

1. Fixed issue with .length being wrong on .load
2. used working syntax for dirty
3. potentially introduced a bug where I wait 5 seconds before killing

made the script work.

**Comment by muxator** [comment]
Do we have a issue on ueberDB for tracking the defect on dirtyDB?

Seems serious enough. How old is the dependency on `dirty` library in ueberDB? Maybe it is time to upgrade?

**Comment by JohnMcLear** [comment]
@muxator  no RE issue on ueber, I figured it was a quirk and easy enough to work around.

Afaik dirty is up to date, I did it recently.

I didn't wanna go too far into fixing or working around deps, I figured for a quick one time use script it doesn't matter if the op is a little slower if it means it's reliable.

**Comment by muxator** [comment]
> it doesn't matter if the op is a little slower

I did not object on the double iteration, indeed. I am just saying that the info about the `length` parameter in ueberDB being broken when using dirtyDB should be written somewhere in ueberDB's code (a comment may be ok, a `warn()` on invocation may be even more evident).

It's a bug and took a lot of time to be discovered, let's not lose it again.

**Comment by JohnMcLear** [comment]
Sorry I was not clear...

The bug appears to be in dirty, or at least the understanding by the initial author of how dirty provides the length value?

**Comment by muxator** [comment]
That's clear, thanks.

Let's add a comment somewhere in https://github.com/ether/ueberDB/blob/master/dirty_db.js to explain that `length` is broken upstream. You spent a lot of time to figure this out, it has to be written somewhere better than in github comments.

I am working on #3956 now.

**Comment by JohnMcLear** [comment]
I put it on the new database reference docs.   dirtyref is branch, I'm stopping my commits to master as dirtyref is ready for review.

**Pull request merged**
