### PR TITLE
Support ejs 2.0

### LINKED ISSUE #2437: console - ReferenceError: ejs:1 ("Sorry, something bad happened")
Hi there,

my last issue was closed, but the error still appears...

I installed Etherpad on CentOS according to this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-etherpad-for-production-with-node-js-and-mysql-on-a-vps

I did a fresh install - unfortunately I'm getting this error:

[2015-01-04 18:08:20.111] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:145)
    at /home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)

If I start etherpad, I'm getting this error:

[etherpad@pad etherpad-lite]$ ./bin/run.sh
Ensure that all dependencies are up to date...  If this is the first time you have run Etherpad please be patient.
npm WARN package.json async-stacktrace@0.0.2 No repository field.
npm WARN package.json channels@0.0.4 No repository field.
npm WARN package.json tinycon@0.0.1 No repository field.
Ensure jQuery is downloaded and up to date...
Clear minfified cache...
Ensure custom css/js files are created...
Started Etherpad...
[2015-01-04 18:11:08.173] [INFO] console - Installed plugins: ep_etherpad-lite
[2015-01-04 18:11:08.192] [INFO] console - Your Etherpad git version is e2ea82f
[2015-01-04 18:11:08.192] [INFO] console - Report bugs at https://github.com/ether/etherpad-lite/issues
[2015-01-04 18:11:08.320] [INFO] console - You can access your Etherpad instance at http://0.0.0.0:9001/
[2015-01-04 18:11:08.321] [WARN] console - Admin username and password not set in settings.json.  To access admin please uncomment and edit 'users' in settings.json

If I try to open etherpad via browser, the browser-output is:

{
  "error": "Sorry, something bad happened!"
}

The console shows:

[2015-01-04 18:11:50.853] [ERROR] console - ReferenceError: ejs:1
 >> 1| <% e._init(buf); %><%
    2|   var settings = require("ep_etherpad-lite/node/utils/Settings");
    3| %>
    4| <!doctype html>

buf is not defined
    at eval (eval at <anonymous> (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:281:12), <anonymous>:2:8000)
    at /home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:307:17
    at Object.exports.render (/home/etherpad/etherpad-lite/src/node_modules/ejs/lib/ejs.js:166:13)
    at Object.exports.require (/home/etherpad/etherpad-lite/src/node/eejs/index.js:122:17)
    at /home/etherpad/etherpad-lite/src/node/hooks/express/specialpages.js:15:19
    at callbacks (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:164:37)
    at param (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/etherpad/etherpad-lite/src/node_modules/express/lib/router/index.js:33:10)
[2015-01-04 18:11:50.920] [INFO] ueberDB - Flushed 1 values

This error was on Debian 7 and now on CentOS - the VPS was always a fresh setup.

### PR DESCRIPTION
**Pull request by TimothyGu**
Fixes #2437.

### CODE REVIEW

**Comment by TimothyGu** [comment]
Note that I decided to use `^2.0.0` which is equivalent to `2.x.x`, so that future minor version bump would still be matched.

**Comment by JohnMcLear** [comment]
Perfect, thanks!

**Comment by mde** [comment]
Does this include the issue with plugins not showing up? Our initial fix unbroke the build, but I'm not sure it was a total fix.

**Comment by JohnMcLear** [comment]
Oh good point mde, I will test that now

**Comment by JohnMcLear** [comment]
it should...

**Comment by JohnMcLear** [comment]
Ah damn no it doesn't ;(  Plugins still not showing up..  I should really have test coverage for that...

**Comment by TimothyGu** [comment]
I'm fine with reverting this commit for now. Just wanted to help.

**Comment by JohnMcLear** [comment]
Yea let's revert for now, hopefully @mde can get a perma fix in :)

**Pull request merged**
