### PR TITLE
Add etherpad update check

### LINKED ISSUE #3937: Update hint
Currently an admin of a etherpad instance gets no notification about a new etherpad release.

What about adding a hint to the admin page?
Any other ideas?

### PR DESCRIPTION
**Pull request by Gared**
This PR checks on static.etherpad.org for the latest etherpad version and will show a hint in the console at runtime and on the troubleshooting page in the admin area.

closes #3937

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Awesome :D

**Comment by JohnMcLear** [comment]
```
[2020-06-01 16:52:47.669] [ERROR] console - Can not perform Etherpad update check: Error: read ECONNRESET
```

**Comment by JohnMcLear** [comment]
No reason why I got an error, retried and it was fine..

**Comment by Gared** [comment]
Just a hint for myself: Need to write a script to update my json everytime a new release is out

**Pull request merged**
