### PR TITLE
Fix the way Content Collector gets the node class. Fixes #2640

### LINKED ISSUE #2640: Content Collector not getting the class value of nodes
I'm using the plugin ep_font_color, and when I change the pad content using the `setHTML()` hook, Etherpad is ignoring the class on my nodes.

Here's the HTML I'm using as content for my pad:
```
<html><body><span class='color:red'>this should be red</span></body></html>
```

Apparently the issue in on `static/js/contentcollector.js`, when getting the class from node:
```
    nodeProp: function(n, p)
    {
      return n[p];
    },
(...)
var cls = dom.nodeProp(node, "className");
```

When using jsdom to read the HTML, the code above works. But when using cheerio it does not:
```
var jsdom = require("jsdom").jsdom;
var doc = jsdom("<html><body><span class='color:red'>this should be red</span></body></html>");
var body = doc.childNodes[0].childNodes[1];
var span = body.childNodes[0];
span["className"];
// => 'color:red'
```
```
var cheerio = require('cheerio');
var $ = cheerio.load("<html><body><span class='color:red'>this should be red</span></body></html>");
var body = $('html')[0].childNodes[0];
var span = body.childNodes[0];
span["className"]
// => undefined

span.attribs["class"];
// => 'color:red'
```

I found a way to fix it, but wanted to be sure this is an issue with Etherpad code, and not on my environment.

### PR DESCRIPTION
**Pull request by lpagliari**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@lpagliari Run all tests?

**Comment by lpagliari** [comment]
@JohnMcLear Yep, both frontend and backend. All passed.

**Comment by lpagliari** [comment]
Hum, so I'm confused about the error TravisCI is showing (`Missing required arguments USERNAME, API_KEY`). I've seen [another pull request] (https://travis-ci.org/ether/etherpad-lite/builds/59600306) with the same error message, and it was accepted, so I'm assuming this error might be related to the CI config, and not the code itself.

I'm a newbie on Etherpad, so I don't know what to do next. Is there anything I can do to fix this?

**Comment by JohnMcLear** [comment]
@lpagliari ah to run the tests on the server do:

``bin/backendTests.sh``

On the frontend browse to ``/tests/frontend``

**Comment by lpagliari** [comment]
@JohnMcLear sorry, I was not clear. I did what you said before creating the pull request, both test suites were passing on my local environment. My question was regarding Travis failure.

**Comment by JohnMcLear** [comment]
Either me or @Pita have to open the PR for us to test w/ Travis..  It's a pain in the ass.

**Comment by lpagliari** [comment]
Ow, ok, got it. Thanks for the support!

**Comment by akshat-g** [comment]
@lpagliari i tried to run backendTests.sh but terminal throws error - 
(without sudo)./backendTests.sh: line 1: src/node_modules/mocha/bin/mocha: No such file or directory

(with sudo)./backendTests.sh: 1: ./backendTests.sh: src/node_modules/mocha/bin/mocha: not found

mocha is installed in my etherpad directory.Also mocha file inside mocha/bin exists. How to get around with this? Do I have to include mocha path in PATH? How did you do that?

**Comment by JohnMcLear** [comment]
@akshat-g read what I wrote.

``bin/backendTests.sh``

**Comment by akshat-g** [comment]
@JohnMcLear  - yeah I did the same but above errors were thrown.

**Comment by JohnMcLear** [comment]
what errors @akshat-g ??

**Comment by akshat-g** [comment]
@JohnMcLear - 
(without sudo)./backendTests.sh: line 1: src/node_modules/mocha/bin/mocha: No such file or directory

(with sudo)./backendTests.sh: 1: ./backendTests.sh: src/node_modules/mocha/bin/mocha: not found

mocha is installed in my etherpad directory.Also mocha file inside mocha/bin exists. How to get around with this? Do I have to include mocha path in PATH?

**Comment by JohnMcLear** [comment]
@akshat-g PLEASE read what I said..  I'm done helping you until you start to listen.

**Comment by lpagliari** [comment]
@akshat-g don't run inside the `bin/` folder, run on the root folder.

This won't work:
```
./backendTests.sh
```

This should:
```
./bin/backendTests.sh
```

Does that work for you?

**Comment by akshat-g** [comment]
@JohnMcLear @lpagliari ok Sorry. I thought ./backendTests.sh should run too. Now it is working thanks. Actually I opened mocha file and found that path relative to root folder is used.

**Pull request merged**
