### PR TITLE
Can you please feed it some real life html?

### PR DESCRIPTION
**Pull request by tudorilisoi**
read here about the HTML filter 
https://github.com/punkave/sanitize-html
... and here about the "forgiving" parser 
https://github.com/punkave/sanitize-html

In the worst case the filter needs some configuration and very bad HTML will pass through, albeit a bit crippled. But it may just work as is.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Does this pass the backend and frontend tests?

**Comment by tudorilisoi** [comment]
Hello, John!Travis says I have no valid key/pass 


     On Saturday, May 16, 2015 10:03 PM, John McLear <notifications@github.com> wrote:
   

 Does this pass the backend and frontend tests?—

**Comment by JohnMcLear** [comment]
You can run the test locally..

bin/backendTests.sh
and frontend tests are at /tests/frontend

**Comment by tudorilisoi** [comment]
Thanks, I will do that. I submitted the patch in a late morning, you know...

**Comment by JohnMcLear** [comment]
You can test locally

On 16 May 2015 22:22, tudorilisoi <notifications@github.com> wrote:
Hello, John!Travis says I have no valid key/pass


On Saturday, May 16, 2015 10:03 PM, John McLear <notifications@github.com> wrote:


Does this pass the backend and frontend tests?—

**Comment by tudorilisoi** [comment]
I will

**Comment by JohnMcLear** [comment]
Yeah sorry my phone is doing weird stuff....

On 17 May 2015 05:47, tudorilisoi <notifications@github.com> wrote:

Thanks, I will do that. I submitted the patch in a late morning, you know...

**Comment by JohnMcLear** [comment]
@tudorilisoi how are you getting on?

**Comment by JohnMcLear** [comment]
@tudorilisoi Bump?

**Comment by Pita** [comment]
Is this work in progress?

**Comment by tudorilisoi** [comment]
@pita this is no feature branch, but a heavily customized EP. I would like to contribute some atomic pull requests, but there's never enough time. One of the highlights is the use of gulp, browserify for bundling and a more proper static assets server for monofication

**Comment by tudorilisoi** [comment]
Minification, sorry, I'm on Android

**Comment by JohnMcLear** [comment]
@tudorilisoi just be aware we will be breaking your changes if you don't commit them or do plugins.

**Comment by tudorilisoi** [comment]
Okay. I'm not disciplined enough to do atomic feature branches

**Pull request closed without merging**
