### PR TITLE
deps: use ci --no-optional flags, this might break some things

### PR DESCRIPTION
**Pull request by JohnMcLear**
might break some things as it requires npm 6.31.4

### CODE REVIEW

**Comment by rhansen** [comment]
This could break users. It might be better to just change our CI tests to use `--no-optional`.

**Comment by JohnMcLear** [comment]
I had a think and I'm not sure how it can break users, unless they use optional sqlite?

**Comment by rhansen** [comment]
> unless they use optional sqlite?

Exactly. I'm one of those users that uses sqlite. :slightly_smiling_face: 

Though I always explicitly do `npm i sqlite3` so this wouldn't affect me personally.

**Comment by JohnMcLear** [comment]
Let's try with it in for a few days :P  See if someone complains

**Pull request merged**
