### PR TITLE
CSP: Move `index.html` inline code to separate `.js` file

### PR DESCRIPTION
**Pull request by rhansen**
Addresses #4401.

### CODE REVIEW

**Comment by rhansen** [comment]
@brunob Before you merge https://framagit.org/infini/ep_infini/-/merge_requests/1 would you test it against this PR? I think it'll still work but I'm not 100% sure because both attempt to set the `onsubit`/`onclick` handlers. We might have to change https://framagit.org/infini/ep_infini/-/merge_requests/1 to use `eejsBlock_indexWrapper` instead.

**Comment by JohnMcLear** [comment]
https://github.com/ether/etherpad-lite/pull/4410/files#diff-b7ed03066e63b832507c09098fed57d4L186 I think is relatively important or was like 3 years ago.  Did this never get wide adoption?   https://www.gnu.org/software/librejs/free-your-javascript.html for details.

If it isn't worth including I don't mind it being dropped.

**Comment by rhansen** [comment]
> https://github.com/ether/etherpad-lite/pull/4410/files#diff-b7ed03066e63b832507c09098fed57d4L186 I think is relatively important or was like 3 years ago.

I added back the annotation.

> Did this never get wide adoption? https://www.gnu.org/software/librejs/free-your-javascript.html for details.

This is the first time I've heard about it.

I just tried that plugin. It is quite terrible:

* It blocks unknown scripts by default, so sites that haven't yet added the annotations (which is most sites) will break.
* There is no way to put it in a report-only mode. If you whitelist a site (so that it still functions) you can't tell what scripts would have been blocked had the site not been whitelisted.
* There's no way to tell it to whitelist everything.
* Annotating scripts is not very dev-friendly. (The poor documentation is only partly to blame.)

I applaud the goal, but it'll never achieve wide adoption unless they change the default behavior to not block.

**Comment by brunob** [comment]
@rhansen just tested it and the overriding of the handlers doesn't work anymore.

**Comment by rhansen** [comment]
Bummer. Thanks for testing @brunob. I'll revise the GitLab merge request and get back to you.

**Pull request merged**
