### PR TITLE
Add author information to the context for padCreate and padUpdate hooks.

### PR DESCRIPTION
**Pull request by xavidotron**
This gives the hooks access to information that's otherwise awkward to get.

Ran backend tests and they pass.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
1. Please include test coverage for the author information.
2. Please test on pads that have no authors (IE blank pads or pads that don't exist).
Should work fine :)

**Comment by xavidotron** [comment]
Is there an example of a test that registers a hook?  I tried to figure out how to write a test, but wasn't sure the best way to register a hook.

I updated the documentation in doc/api/hooks_server-side.md.  I don't think there's anything to update with the API endpoints, since this is just changing a server-side hook, not an endpoint.  Is there anywhere else I need to document this?

**Comment by JohnMcLear** [comment]
Can't think of an example of a plugin that uses a hook, should work okay anyways.

**Comment by JohnMcLear** [comment]
tnx

**Pull request merged**
