### PR TITLE
Adding api call for appending a chat message.

### PR DESCRIPTION
**Pull request by derosm2**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Looks good!  Please add this API call to the backend tests! :)
https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/pad.js

You could also add other tests for chat now that the backend tests can make chat messages!  That's awesome, let me know if you need help!

**Comment by derosm2** [comment]
Haven't had a chance to write up the tests yet, but will do so when I get some free time!

**Comment by JohnMcLear** [comment]
Bump @derosm2

**Comment by JohnMcLear** [comment]
Moving here: https://github.com/ether/etherpad-lite/pull/2573

**Pull request closed without merging**
