### PR TITLE
Fix value to be valid JSON.

### PR DESCRIPTION
**Pull request by danfuzz**
Also fixed some errant EOL whitespace.

### CODE REVIEW

**Comment by danfuzz** [comment]
Hi! Just a quick little PR I put together to test the waters for the contribution process. Thanks for your consideration.

**Comment by danfuzz** [comment]
Not sure what's going wrong with Travis. The build worked for me locally, but also the only changes I made were in comments.

**Comment by lpagliari** [comment]
@danfuzz I've seen Travis having the same issue on other builds of Etherpad, it might not be directly related to your commit

**Comment by danfuzz** [comment]
@lpagliari: Thanks for the info, and thanks for the merge!

**Pull request merged**
