### PR TITLE
Bump ueberDB version

### PR DESCRIPTION
**Pull request by Gared**
See https://github.com/Pita/ueberDB/pull/88

### CODE REVIEW

**Comment by Gared** [comment]
@JohnMcLear Can you please upload the new version of ueberDB to npm?

**Comment by JohnMcLear** [comment]
24 verbose stack Error: Invalid name: "ueberDB"

**Comment by JohnMcLear** [comment]
Done

**Comment by Gared** [comment]
@JohnMcLear I don't get it. What have you done and why did you close my PR?

**Comment by JohnMcLear** [comment]
I pushed ueberdb2 which is a new version.  npm no longer supports pushing to modules with capitalis in the name.

**Comment by JohnMcLear** [comment]
I also bumped ueberdb version in the etherpad package.json..  look at the commits!

**Pull request closed without merging**
