### PR TITLE
Fix AbiWord wikilink and capitalization

### PR DESCRIPTION
**Pull request by HairyFotr**
Going through translatewiki.net for this case would be very hard, I hope a PR is ok.

### CODE REVIEW

**Comment by lpagliari** [comment]
Sorry, @HairyFotr , this does not work because the locale files are generated avery few weeks, so your changes would be overwritten on the next locale update. You need to go through the languages on translatewiki.net :-/

**Comment by HairyFotr** [comment]
I've noticed that English, as the source language, is not editable on translatewiki. Should I instead make a PR with just the English fix, and then (I'm guessing) translatewiki will mark all other translations as "outdated", and they'll eventually get fixed?

**Comment by lpagliari** [comment]
Hum, good point. Yes, I believe that would work. If you want, just update this PR here.

**Comment by HairyFotr** [comment]
Ok, updated.

**Comment by lpagliari** [comment]
Tks

**Pull request merged**
