### PR TITLE
Dont store authd users in database

### PR DESCRIPTION
**Pull request by JohnMcLear**
To try to resolve: https://github.com/ether/etherpad-lite/issues/4016

I can't see why you would want to have auth'd sessions persist in the database.  They are in the settings file anyway..  Thoughts?  Will this break something?  Tests pass...  

Opinions welcome.

### CODE REVIEW

**Comment by rhansen** [comment]
Please rebase f6eae1ba onto develop (your fork's develop branch has some unnecessary merge commits).

**Comment by JohnMcLear** [comment]
My forks a huge mess.  I'm waiting on merging a lot of pulls before fixing it up.  I think it's a mess because I pull ether develop onto my develop through the web UI instead of pulling through cli or something..  so fixing it is a no go for me because I suck at git.  If you wanna help me out not suck at git I can try!

**Comment by rhansen** [comment]
Unfortunately it's way too easy to suck at Git.  :smile:

To fix your fork:

```
git clone git@github.com:JohnMcLear/etherpad-lite.git
cd etherpad-lite
git checkout develop
git reset --hard origin/develop
git push -f -u origin develop
```

After that, to fix your `dont-store-authd-users-in-database` branch:

```
git checkout dont-store-authd-users-in-database
git rebase --onto origin/develop HEAD^
git push -f -u origin dont-store-authd-users-in-database
```

**Comment by rhansen** [comment]
Unfortunately it's way too easy to suck at Git.  :smile:

To fix your fork:

```
# clone the upstream ether/etherpad-lite repo (origin refers to the ether/etherpad-lite repo)
git clone https://github.com/ether/etherpad-lite.git
# add a remote named "JohnMcLear" for your fork
git remote add JohnMcLear git@github.com:JohnMcLear/etherpad-lite.git
# fetch the commits from your fork
git remote update -p
# check out your fork's develop branch
git checkout -b develop JohnMcLear/develop
# change your local working directory's develop branch to match origin/develop
git reset --hard origin/develop
# force update your fork's develop branch to match your working directory's develop branch
git push -f
```

After that, to fix your `dont-store-authd-users-in-database` branch:

```
git checkout -b dont-store-authd-users-in-database JohnMcLear/dont-store-authd-users-in-database
# move the tipmost commit onto the develop branch
git rebase --onto origin/develop HEAD^
git push -f
```

**Comment by rhansen** [comment]
This PR seems to break fetching of static content for me.

**Comment by JohnMcLear** [comment]
What do you get when trying to fetch static?  What response code?  Will rebase for you, not tonight though, 2mrw AM.

**Comment by rhansen** [comment]
I'll check.

In the meantime, would you mind merging PR #4023? Storing the plaintext password in the database is better than allowing anyone to log in with the password "PASSWORD_HIDDEN".

**Comment by JohnMcLear** [comment]
I'm trying to not merge stuff atm because I'm so active as a contributor, @muxator is doing a great job in that role and I don't wanna step on his toes.  He should be online in ~2 hours if his usual crazy schedule is anything to work by

**Comment by rhansen** [comment]
I'm not exactly sure what's going wrong. Transfers seem to get stuck—my NGINX reverse proxy is timing out and throwing 504s.

**Comment by JohnMcLear** [comment]
I "hopefully" fixed my git repo :|

**Comment by rhansen** [comment]
I don't have a good understanding of Etherpad internals, but from what I can tell the current develop branch uses the basic auth header only when establishing a new session. After the session is saved in the database the client only needs the express-session secure cookie for continued access (the client doesn't need to set the basic authentication header).

With this PR, the session is no longer saved in the database and the client needs the authentication header in every request. Maybe each request ends up generating a new session ID which breaks stuff?

> I "hopefully" fixed my git repo

Looks good to me, thanks!

**Comment by JohnMcLear** [comment]
Yea I see that bug too, to replicate visit ``/admin``

I think we revert my initial fix and I will put something in that encrypts the password using the token as the salt...

**Comment by JohnMcLear** [comment]
I pushed another approach but it's not working properly.  The new approach encrypts the password before storing it to the database, and on query it decrypts.  But it doesn't work after first auth.

**Pull request closed without merging**
