### PR TITLE
Feature: Read Only Chat Issue #2672

### PR DESCRIPTION
**Pull request by bhldev**
Feature Read Only Chat Issue #2672 and default settings in settings.json on the client side for future use

### CODE REVIEW

**Comment by Gared** [comment]
I don't get the idea behind your code.
When is a user able to send a chat message?
As far as I can see the check is only on client side and not on server side, so a user can easily circumvent your check...

**Comment by bhldev** [comment]
Added server side check, user can send a chat message by default
When readOnlyCanCommentAndChat is set to false in settings.json, chat is disabled in etherpad according to feature request #2672

**Comment by bhldev** [comment]
Hello,
Can this be approved and merged or closed?
Thanks,
~ B

**Comment by JohnMcLear** [comment]
Sorry been busy, is this still a feature you want?  What issue does this pull request solve?

**Pull request closed without merging**
