### PR TITLE
Unix domain socket support.

### PR DESCRIPTION
**Pull request by iia**
Based on this [issue](https://github.com/ether/etherpad-lite/issues/3299) this PR tries to add a new feature with which Etherpad Lite can be reached locally with a UNIX domain socket and also enable Systemd socket activation. The implementation adds a new dependency to the **autoquit** module.

To test the implementation:

1. Enable the **unixSocketActivation** configuration option.

2. Add Systemd service and socket files,

- Service File (/etc/systemd/system/etherpad-lite.service)
```
[Unit]
Description=Etherpad Lite, the collaborative editor.
After=syslog.target network.target
Requires=etherpad-lite.socket

[Service]
Type=simple
User=<USER>
Group=<GROUP>
WorkingDirectory=<INSTALL_DIRECTORY>
ExecStart=<NODEJS_BIN_PATH> <INSTALL_DIRECTORY>/src/node/server.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=etherpad-lite
Restart=no

[Install]
WantedBy=multi-user.target
```

- Socket File (/etc/systemd/system/etherpad-lite.socket)
```
[Unit]
Description=Etherpad Lite socket for UNIX socket activation.
PartOf=etherpad-lite.service

[Socket]
ListenStream=/tmp/etherpad-lite.socket
Accept=False

[Install]
WantedBy=sockets.target
```

3. Enable the socket with the following commands,

```
sudo systemctl --system daemon-reload
```
```
sudo systemctl start etherpad-lite.socket
```

4. Test Etherpad Lite functionalities,

- HTTP GET request

```
curl --unix-socket /tmp/etherpad-lite.socket -X GET http:/
```

- HTTP REST API: Create a pad

```
curl --unix-socket /tmp/etherpad-lite.socket \
-d '{"apikey":"<API_KEY>", "padID":"<PAD_ID>", "text": "<TEXT>"}' \
-H "Content-Type: application/json" \
-X POST http:/api/1/createPad
```

- HTTP REST API: Set text of the created pad

```
curl --unix-socket /tmp/etherpad-lite.socket \
-d '{"apikey":"<API_KEY>", "padID":"<PAD_ID>", "text": "<TEXT>"}' \
-H "Content-Type: application/json" \
-X POST http:/api/1/setText
```

- HTTP REST API: Get text from the created pad

```
curl --unix-socket /tmp/etherpad-lite.socket \
-d '{"apikey":"<API_KEY>", "padID":"<PAD_ID>"}' \
-H "Content-Type: application/json" \
-X POST http:/api/1/getText
```

### CODE REVIEW

**Comment by lpagliari** [comment]
@rhelmer can you take a look on this, please?

**Comment by JohnMcLear** [comment]
Bump @rhelmer

**Comment by muxator** [comment]
Hi,

we are already _unknowingly_ "supporting" unix sockets. A user found a minor bug because of this: #3437.

This configuration snippet actually results in etherpad listening to a unix socket:
```javascript
// settings.json
{
  "ip": "",                               // <-- empty string
  "port" : "/somepath/etherpad.socket",   // <-- path to a Unix socket
  // ...
}
```

This is due to [`express.listen()`](http://expressjs.com/en/4x/api.html#app.listen_path_callback), which in turn just [re-exposes `net.server.listen()`](https://nodejs.org/api/net.html#net_server_listen) and its overloads, including the one that binds on a Unix socket.

This PR makes it **explicit**, and this is certainly desirable.
Let me propose what should be added before merging:

## Important
1. [ ] suitable examples for binding Etherpad to a Unix socket should be added in `settings.json.template`
2. [ ] the timeout for `autoQuit()` should be configurable in `settings.json` (and documented in `settings.json.template`)
3. [ ] if one does not want to use automatic quitting, a value of `0` for the timeout should completely bypass the feature (since, [reading autoquit's source](https://github.com/rubenv/node-autoquit/blob/master/lib/autoquit.js), there is no way of starting autoquit in a disabled state)
4. [ ] once this PR is ready, a last commit should be added to make stricter validation of `settings.ip` and `settings.port` in order to make mandatory the use of the new configuration options (making impossible the bypass described above).

## Nice to have
1. [ ] the examples with service and socket files are really useful, and worth putting in a documentation file (maybe a new one)?
2. [ ] The [wiki about reverse-proxying](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy) is worth at least an example about using Etherpad as an upstream bound to a unix socket.

**Comment by muxator** [comment]
This would be a good moment to work on this PR, since we are at the start of a new cycle.

**Comment by iia** [comment]
Hi @muxator,

Already looking into the requests.

Cheers.

**Comment by muxator** [comment]
Hi @iia, give a voice if you need help.

**Comment by iia** [comment]
Hi,

Sorry for the late reply. While trying to follow the instructions of this PR on the branch of this PR I couldn't make the API POST to work. GET seems to work OK.

I'm getting a, **405: Only the HEAD or GET methods are allowed.**

I suspect it has something to do with the order of things in ep.json hooks and how they are loaded.

Any ideas?

Cheers.

**Comment by muxator** [comment]
I have a doubt now: this change is systemd-specific.

Would Etherpad still run if executed in an environment without systemd? For Example, on Windows, or on Alpine Linux, of in a container (which has no notion of PID 1).

Considering [we are already unknowingly supporting unix domain sockets](https://github.com/ether/etherpad-lite/pull/3312#issuecomment-412340758), I am starting to think if a different approach could make sense:

1. document the possibility of using unix domain socket on supported platforms, without introducing a new configuration parameter
2. deduce at runtime (from the value of the listen config parameter) if we are binding to a network or unix socket
3. keep the helpful message logs at startup which indicate in which mode Etherpad is running
4. discuss the useful autoquit functionality in a different PR

**n.b.**: this is not a comment about systemd, but about platform support

**Comment by JohnMcLear** [comment]
-1 Autoquit.

PR coming for changes requested.

**Comment by muxator** [comment]
We are good to go with the already existing Unix socket support.

Merging #3790, which receives [my considerations above](https://github.com/ether/etherpad-lite/pull/3312#issuecomment-412340758), and closing this.

**Pull request closed without merging**
