### PR TITLE
Test coverage and backend support for setHTML.

### PR DESCRIPTION
**Pull request by JohnMcLear**
don't merge yet, I still need to add full test coverage

1) Reports correct failure for setHTML
2) Provides setHTML test coverage
3) Ultimately needs to provide functionality to create li intented stuff 

Attempting to add test coverage for https://github.com/ether/etherpad-lite/issues/1604

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@webzwo0i note below..  Do you have a test case for this in your coverage?  It appears we miss the case where a user might have empty nested ul's as below..

```
  // will fail due to https://github.com/ether/etherpad-lite/issues/1604
  // reminder to self this is how the HTML looks
  // <ul>
  //   <li>one</li>
  //   <li>2</li>
  // </ul>
  // <br>
  // <ul class="bullet">
  //   <ul class="bullet">
  //     <li>UL2</li>
  //   </ul>
  // </ul>
  // It will look right in the browser but the export will get it horriby wrong

  // This is what the export puts out
  // <ul class="bullet">
  //  <li>one</li>
  //  <li>2</li>
  // </ul>
  // <br>
  // <ul class="bullet">
  // NOTE THIS IS WHAT'S MISSING
  //   <li>UL2</li>
  // </ul>
  // <br>
```

**Comment by webzwo0i** [comment]
:-( did you set the html via API or manually in the browser?
I tried to replicate but if I put your html in importexport.js (one time with "br" - this will close the first ul, then newline, then open two uls; the other time without "br" it won't close the first ul and just open one other ul) everything seems to be okay.
So I wonder if there is some difference between setting via API and setting directly in the editor/doing an import.

**Comment by webzwo0i** [comment]
r u sure this is still a problem? I see that you have this in the backend tests ("ULhtml") and I think it works (currently only the "import crappy html"-test fails).
I will add a case for this to the frontend-tests but as I said above it also seems to work there (with and without the newline)

**Comment by JohnMcLear** [comment]
Yea should be okay now, I updated the tests (see above)

**Pull request closed without merging**
