### PR TITLE
Save Only On First Revision #2740

### PR DESCRIPTION
**Pull request by bhldev**
Creates setting to save only on first pad revision feature request #2740

### CODE REVIEW

**Comment by Gared** [comment]
This doesnt't look good to me. What happens if you write a chat message without editing the pad?
I would expect that the first entry to the database will be written when also something pad related should be written to the database (like chat messages, authors, etc.).
I think these change may have some ugly side effects on hooks or something like that. Needs to be tested...

**Comment by bhldev** [comment]
Can't get the frontend tests to work with localhost, cross origin error
Also using dirtydb, real tests should use a real database
I will have to look at this later in the month, if someone else hasn't

**Comment by JohnMcLear** [comment]
+1 @Gared this causes more problems than it solves?

**Comment by bhldev** [comment]
Closing, will resubmit if/when I can think of a better solution

**Pull request closed without merging**
