### PR TITLE
Github Action Fix for Windows build (2)

### PR DESCRIPTION
**Pull request by SamTV12345**
Attempt to fix the windows pipeline build.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
``ERROR: Please install wget`` :P

**Comment by SamTV12345** [comment]
Yep I hate Windows in this regard. It works locally but not on the remote GitHub runner 🤣. I need to do some work and check why it's not working.

**Comment by JohnMcLear** [comment]
I pushed a branch that fixes it, if you wanna compare to that :P

**Comment by SamTV12345** [comment]
Yes I saw that. You were faster so you have the honor to merge your branch xD.

**Pull request closed without merging**
