### PR TITLE
Show chat fix - Ready for review/merge @muxator

### PR DESCRIPTION
**Pull request by JohnMcLear**
Fixes https://github.com/ether/etherpad-lite/issues/3541

I'm wondering if we can have test coverage for this...?

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Bump @muxator

**Comment by muxator** [comment]
Is this still WIP?

**Comment by JohnMcLear** [comment]
Yes.  I want full test coverage.

**Comment by muxator** [comment]
What about the test coverage here? Still WIP?

**Comment by JohnMcLear** [comment]
Sorry I should have said, yeah it's test covered.

**Comment by muxator** [comment]
Ok

**Pull request closed without merging**
