### PR TITLE
contentcollector fixes

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* lint: Fix some straightforward ESLint errors
* tests: Re-enable import/export test that is now working
* tests: Delete invalid contentcollector test
* tests: Fix invalid HTML in contentcollector tests
* tests: Delete erroneous `describe()` calls
* tests: Use `assert.deepEqual()` to simplify equality checks
* tests: Replace "expected" with "want", "received" with "got"
* tests: Fix missing call to `done` callback
* openapi: Fix error logging
* contentcollector: Delete unused `domInterface` parameter
* contentcollector: Document the `dom` object
* contentcollector: Factor out call to `.toLowerCase()`
* contentcollector: Fix Element attribute accesses
* contentcollector: Rename `dom` functions for consistency with DOM spec
* contentcollector: Avoid `for..in` iteration of object properties
* contentcollector: Fix iteration over child Nodes
* contentcollector: Delete unnecessary truthiness check
* contentcollector: Invert logic to improve readability
* contentcollector: Use destructuring to improve readability
* contentcollector: Fix collectContentLineText hook
* contentcollector: Delete unnecessary parentheses
* contentcollector: Fix parent node access
* contentcollector: Fix Element tag name fetch
* contentcollector: Skip over non-Text, non-Element Nodes
* contentcollector: Simplify child node access
* contentcollector: Delete unnecessary `dom` functions

cc @webzwo0i

### CODE REVIEW

**Comment by JohnMcLear** [comment]
``npx mocha ../tests/backend/specs/contentcollector.js`` failing

**Comment by rhansen** [comment]
> `npx mocha ../tests/backend/specs/contentcollector.js` failing

Fixed.

**Comment by JohnMcLear** [comment]
The big change here I'm just double checking about is the removal of ``cheerio``, will check which plugins this might break if any before merging 👍🏽

**Comment by JohnMcLear** [comment]
```
./ep_announce/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_webrtc/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_limit_maximum_number_of_users_on_pad/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_google_analytics/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_copypad/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_sticky_attributes/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_defaultPadText/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_offline_edit/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_comments_page/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
./ep_font_family/node_modules/eslint/package.json:84:    "cheerio": "^0.22.0",
```
The most concerning ones are (ep_comments are ep_readonly_guests)
```
./ep_comments_page/exportHTML.js:3:const $ = require('ep_etherpad-lite/node_modules/cheerio');
./ep_comments_page/exportHTML.js:23:  // https://github.com/cheeriojs/cheerio/issues/1031
./ep_readonly_guest/index.js:3:const $ = require('cheerio');

```

So

1) Why does ``eslint`` require ``cheerio``?
2) How will we handle the transition?  Surely we should keep cheerio in for a few versions until plugins have had time to migrate to JSDom?
3) We should provide either PRs to projects that need to migrate AND/OR docs (quick guides for what to change from>to).
4) Why have our tests not picked up that these projects will fail?

**Comment by rhansen** [comment]
> * Why does `eslint` require `cheerio`?

Looks like eslint has a way to generate a report in HTML. But whether eslint uses cheerio or not doesn't affect us, especially since it's a dev dependency

> * How will we handle the transition?  Surely we should keep cheerio in for a few versions until plugins have had time to migrate to JSDom?

The only plugins that have to change are those that call `collectContent()` (are there any?). Otherwise, they can continue to use cheerio without any issues, so long as cheerio is in their dependencies and they're not piggybacking off of Etherpad's cheerio dependency. (In other words, `require('cheerio')` is fine, `require('ep_etherpad-lite/node_modules/cheerio')` is not.)

> * Why have our tests not picked up that these projects will fail?

As far as I know, the only plugin this affects is ep_comments_page which will be fixed by https://github.com/ether/ep_comments_page/pull/186.

I'm going to move the cheerio to jsdom commit to a separate PR so that it doesn't hold up merging the other commits in this PR.

**Comment by rhansen** [comment]
> I'm going to move the cheerio to jsdom commit to a separate PR so that it doesn't hold up merging the other commits in this PR.

I removed that commit from this PR. Once this PR is merged I'll open a new PR for switching from cheerio to jsdom.

**Comment by JohnMcLear** [comment]
re ran core dumped test

**Comment by rhansen** [comment]
> re ran core dumped test

I've been seeing that a lot lately. There must be a bug in node.js that we're somehow triggering. I don't think it can be a bug in our code because it shouldn't be possible for javascript code to cause node.js to abort.

**Comment by rhansen** [comment]
Re-ran the tests yet again and this time they passed. ¯\\\_(ツ)\_/¯

**Comment by JohnMcLear** [comment]
Merging with the knowledge another PR is coming for the cheerio > jsdom

**Pull request merged**
