### PR TITLE
add docker dev setup

### LINKED ISSUE #6156: Add docker development setup
* * *

name: Feature request
about: Suggest an idea for this project
title: 'docker development setup'
labels: enhancement
assignees:

* * *

**Is your feature request related to a problem? Please describe.**
Currently, the docker setup for developers is a bit complicated. The docker build is by default production. It should allow both options (development and production).

**Describe the solution you'd like**
A docker file that lets you choose from development or production and a docker compose file for an easy setup.

### PR DESCRIPTION
**Pull request by JannikStreek**
This pull-request features the following:

- Added development setup for docker. A target can be used to select between development and production
- Added a docker compose file for easier setup (also possible to use this for production)
- Integrated pnpm into docker
- For security purposes made the COPY in production more precise; e.g. copy dedicated git files separately instead of copying everything, which might result in security vulnerabilities when accidentally including sensitive files.

closes #6156, #5169

### CODE REVIEW

**Comment by SamTV12345** [comment]
Hi Jannik, 

thanks for the pull request. This looks awesome and will definetely help getting started with etherpad. I am currently wondering why the image size increased that much: 

Before:
image

After building with docker build --target production -t etherpad/etherpad:develop .:
image

**Comment by JannikStreek** [comment]
@SamTV12345 thanks for the feedback, I will double check where the size is coming from.

**Comment by JannikStreek** [comment]
@SamTV12345 I think I found the reason, can you check again? For some reason `RUN chmod -R g=u .` increases the image size by 50 mbs...I commented removed it for now, as it was before. I also added a readme section to explain the compose setup.

**Review by SamTV12345 — APPROVED** [review]
Thanks for raising this pull request.

**Pull request merged**
