### PR TITLE
When using setText(), replace the entire existing text of the pad.

### PR DESCRIPTION
**Pull request by xavidotron**
Fix setText() to replace the full pad text rather than replacing all except the last letter.  Previously, e.g., calling setText() with a pad's existing contents would make the pad one character longer.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Do me a favor and quickly run ``bin/backendTests.sh`` -- this looks fine but I want to ensure it's not affecting anything else.

**Comment by xavidotron** [comment]
Thanks!  The tests did depend on the old behavior, so I added a commit to fix them.  The tests also revealed that my change broke setPadHTML(), which seems to depend on setText('') leaving a single newline character in the pad.  I don't understand the implementation of setPadHTML() enough to understand the failure, but changing that line to setText('\n') seems to fix the test.

**Comment by JohnMcLear** [comment]
Okies, prolly worth running the frontend tests just to be sure nothing else got b0rked.

http://youretherpad.com/tests/frontend

Once they pass we should be good to merge :)

**Comment by xavidotron** [comment]
Frontend tests pass without issue.  Thanks!

**Comment by JohnMcLear** [comment]
Thanks :)

**Comment by JohnMcLear** [comment]
@xavidotron looks like @LaKing found a bug with your commits, can you take a look at #2700 please?

**Comment by JohnMcLear** [comment]
@LaKing can you please do me a favor and include a backend test that replicates your issue?  That way we can ensure it doesn't happen again :)

**Comment by LaKing** [comment]
@JohnMcLear  I would need help on that. The bug is propably backend side, but it shows up on the frontend when using the test plugin. ...

**Pull request merged**
