### PR TITLE
Fix chrome alignment

### PR DESCRIPTION
**Pull request by CupCakeArmy**
Fix for issue #3604

### CODE REVIEW

**Comment by muxator** [comment]
That's weird, does not work for my browser.

```
$ chromium-browser --version
Chromium 73.0.3683.103 Built on Ubuntu , running on Ubuntu 19.04
```

Just deployed on https://beta.etherpad.org, cleared `<basedir>/var/minified*` and restarted (so everything is clean).

@CupCakeArmy, any hints?

**Comment by seballot** [comment]
The changes is not deployed properly, do not why...
in https://beta.etherpad.org I got the following code from `index.css`
image

Change `top: 0` is not there

**Comment by muxator** [comment]
Thanks @seballot. Indeed, I there is a small overlook in the PR. The `top: 0` statemente was added to the wrong block :)

https://github.com/CupCakeArmy/etherpad-lite/blob/ee383664adec624a9f443a9d774195fa92a95f5f/src/static/skins/colibris/index.css#L77-L83

@CupCakeArmy, would you mind:
- fixing the PR and
- transcribing the problem description in the commit message togheter with the refrence to issue #3604?

Thanks a lot!




**p.s.**: I have manually fixed in https://beta.etherpad.org/static/skins/colibris/index.css and the change seems ok, indeed.

**Comment by CupCakeArmy** [comment]
This is weird... it is fixed for me in https://beta.etherpad.org/.
I've put the `top: 0;` in the `#padname`, which is the id of the ok field. Something with the deployment must be wrong. Is there any way to test this locally?

**Comment by CupCakeArmy** [comment]
PR is updated

**Comment by muxator** [comment]
Folded the commits, updated the commit message and pulled in.

Thanks.

**Pull request merged**
