### PR TITLE
Timeout logic - Ready for review

### PR DESCRIPTION
**Pull request by JohnMcLear**
Solution for https://github.com/ether/etherpad-lite/issues/3830

- [x] Doesn't allow edit when in a disconnected state (dunno how that happened).
- [ ] Doesn't make for badchangeset upon reconnection
OR
- [x] Temp fix in place which is not as great a UX but works fine.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Okay I only have time for a temp fix that reloads the pad upon reconnect, it's not ideal but it works.

**It is a vastly better UX that what's currently in develop** but really the pad contents should reload without an entire page refresh.  At least an entire page refresh in Etherpad is cheap but still, it's hacky.

**Comment by muxator** [comment]
Scheduled for **1.8.4**.

**Comment by muxator** [comment]
> At least an entire page refresh in Etherpad is cheap

It is when Etherpad runs in production mode. Otherwise is super slow. I'm thinking about changing the default running mode to production for this reason. Developers can switch it back if they want.

**Comment by JohnMcLear** [comment]
I'm inclined to agree RE auto deploy as production.

**Comment by JohnMcLear** [comment]
Feels like this can be merged?

**Comment by rhansen** [comment]
Would you mind rebasing this onto current develop?

```
git checkout timeout-logic
git rebase origin/develop
git push -f
```

**Comment by JohnMcLear** [comment]
done

**Comment by JohnMcLear** [comment]
@rhansen if you can do reviews/lemme know if things work it might speed things up with the backlog of PRs?  I rebased a bunch of other PRs.

**Comment by rhansen** [comment]
Thanks for rebasing.

I'm going to test this PR to see if it reduces the number of spontaneous mid-edit disconnects I'm seeing. Unless this PR breaks something horribly, I probably won't be able to report back until the next round of heavy usage on my Etherpad a week from now (for a weekly meeting).

**Comment by rhansen** [comment]
With this PR merged in, I have a large pad that keeps reloading itself over and over on its own.

The pad is 967 lines long (many of of those lines are actually long paragraphs), about a dozen authors, and months of edit history. It takes about 55 seconds to load on my machine (`NODE_ENV=production`, sqlite3 database).

Could the long load times be triggering a connection timeout which then triggers the reload?

**Comment by JohnMcLear** [comment]
Can you hit me up with a ``.etherpad`` export file.  I get the whole "weekly meeting" thing but if you can be if you want me to help you (essentially for free) I kinda need you to reciprocate...

Fwiw I dropped sqlite3 on the next version of ueber so is that a deal breaker for you?

**Comment by rhansen** [comment]
> Can you hit me up with a `.etherpad` export file.

Sent you an email with the export attached.

More details about my Etherpad setup:
  * Current tip of `develop` branch (f79b50d3118401b4ff5f457a1188e861a1ec0c54)
  * Run in a Docker container
  * `NODE_ENV=production`
  * Plugins:
    * ep_adminpads2
    * ep_align
    * rhansen/ep_author_neat
    * ep_delete_empty_pads
    * ep_font_color
    * ep_font_family
    * ep_font_size
    * ep_headings2
    * ep_padlist2
    * ep_prompt_for_name

> Fwiw I dropped sqlite3 on the next version of ueber so is that a deal breaker for you?

I can spin up a PostgreSQL server and feed it a dump of the sqlite3 database if necessary, but I'd rather stick with sqlite3. I like sqlite3 because it's low maintenance: (a) It's trivial to back up the database, (b) it's trivial to move the database to another server, (c) I don't have to worry about username+password management, and (d) I don't have to worry about accidentally exposing a TCP port to the world.

**Comment by rhansen** [comment]
Without this PR, I get a silent disconnect (no pop-up) after the pad finishes loading and all edits are silently discarded. So I guess the behavior with this PR is better than without—at least I know it's broken. :smile:

**Comment by rhansen** [comment]
Another thing to note: I tried Chromium (I usually use Firefox) and it loaded much faster and did not disconnect when it finished loading.

**Comment by JohnMcLear** [comment]
Pad loads in about 1 second for me. 

Initial load is slow because it's creating minified JS/CSS.

Can you see if disabling plugins makes a difference?  

I'm using dirtydb, no plugins, firefox.

**Comment by rhansen** [comment]
I'll do some more troubleshooting to see if I can identify the source of slowness.

Ignoring my particular setup, I think that merging this PR is better than not. Users with slow servers, slow clients, or massive pads might start complaining about reload loops, but without this PR I think those reload loops would instead be silent discards, and that's worse.

Thoughts for a future PR (or this one if you feel up to it):
  * Is it feasible to replace the automatic reload with a "you have been disconnected" pop-up? Would that be better?
  * I'm curious to know what's causing the infinite reload loop, and whether the initial pad load can be restructured to avoid it. I don't know much about Etherpad's internals, but I suspect there's some sort of heartbeat (WebSockets ping/pong?) that continually tests the connection health, and if a heartbeat times out it triggers a reconnect. If that's true, I wonder if it's possible to postpone starting the heartbeats until the pad has finished its initial load.

**Comment by rhansen** [comment]
The slowdown I'm experiencing seems to be caused by the ep_author_neat plugin (clkao/ep_author_neat#17).

Please merge this. The lost edits bug is severe enough that this should be merged, even if improvements could be made. (Those improvements can be made in a future pull request.)

**Pull request merged**
