### PR TITLE
plugins: Use `npm ls` to list the installed plugins

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* /admin/plugins: Fix logging of error messages
* GitHub workflows: Install Node.js v12
* plugins: Helper function to run the `npm` CLI
* plugins: Use `npm ls` to list the installed plugins

Using `npm ls` to list the plugins speeds up startup considerably with v7.x, and we get rid of a lot of buggy code.

This works with both npm v6.x and v7.x.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Will review this today

**Comment by rhansen** [comment]
Still trying to figure out why Docker isn't happy. I can reliably reproduce it—`npm ls` shows nothing inside Docker even though it shows stuff in `node_modules/` when run outside of Docker.

**Comment by rhansen** [comment]
> Still trying to figure out why Docker isn't happy.

I figured it out: `npm ls` won't show anything unless there is either an appropriate `package.json` or `NODE_ENV` is set to `development` (or unset). Docker sets `NODE_ENV` to `production`. Fixes have been pushed, so this is ready to review.

**Comment by JohnMcLear** [comment]
Seems to be a fair amount of consistent test failure?

**Comment by JohnMcLear** [comment]
Looks more hopeful now, will let tests run then do final review and then hopefully this will get merged :)

**Comment by JohnMcLear** [comment]
I'm seeing some weird behavior but I'm 99.9% sure it's not related to this PR.  I just want to be 100%...

**Comment by risacher** [comment]
If I install a plugin from a local directory, then it shows up in package-lock.json, but 'npm ls' (as invoked in plugins.js: 'npm ls --long --depth=0 --json --no-production') does not show it in '.dependencies', but rather in '._shrinkwrap.dependencies'.  As a result, etherpad-lite does not load the plugin.  Under the current system, what is the proper way to install a plugin from local files (i.e. during development)?

```
magnus@aspen:~/etherpad-lite$ src/node_modules/.bin/npm install ./ep_linkify2
npm WARN saveError ENOENT: no such file or directory, open '/home/magnus/etherpad-lite/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/magnus/etherpad-lite/package.json'
npm WARN etherpad-lite No description
npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No README data
npm WARN etherpad-lite No license field.

+ ep_linkify2@0.1.1
updated 1 package and audited 979 packages in 9.058s

89 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

magnus@aspen:~/etherpad-lite$ src/node_modules/.bin/npm ls --long --depth=0 --json --no-production|jq '.dependencies|keys'
[
  "colors",
  "domhandler",
  "ep_adminpads2",
  "ep_etherpad-lite"
]
magnus@aspen:~/etherpad-lite$ src/node_modules/.bin/npm ls --long --depth=0 --json --no-production|jq '._shrinkwrap.dependencies'|grep linkify
  "ep_linkify2": {
    "version": "file:ep_linkify2"
```

**Comment by webzwo0i** [comment]
Try `npm link` in the project directory of your plugin and then npm link plugin-name in Etherpad's main directory

**Comment by risacher** [comment]
Thanks for the quick response.  Not sure if this amounts to the same thing, but adding a peerDependency in the package.json of the plugin seems to have fixed my issue.  My plugin still doesn't work, but at least now it _loads_.
```
peerDependencies": {
    "ep_etherpad-lite": ">=1.8.6"
  },
```

**Pull request merged**
