### PR TITLE
Fix freeze on pad deletion

### PR DESCRIPTION
**Pull request by Chocobozzz**
Fix freeze on pad deletion (if it has many revisions)

Needs https://github.com/Pita/ueberDB/pull/118 first (because of https://github.com/Pita/ueberDB/pull/118/files#diff-0a774d4a9cc6e6d690c76811449906c1R214)

### CODE REVIEW

**Comment by muxator** [comment]
Now that we implemented #3540 this patch should be adapted to `async`/`await` style.

**Comment by raybellis** [comment]
I think this needs to be tested with the async version to see whether it still even causes any freezes.

The new code doesn't explicitly wait for any of the `db.remove()` operations to complete before returning, they're all just sent to the backend database engine asynchronously.

**Comment by Chocobozzz** [comment]
@raybellis yes we wait: https://github.com/ether/etherpad-lite/pull/3562/files#diff-89eec47c9f1563e5a2c346b4a649a7f0R680

**Comment by raybellis** [comment]
Sorry, I was talking about the new _async_ code in the `develop` branch, not the new code in your patch.

**Comment by muxator** [comment]
@Chocobozzz, any chance you are able to forward port this fix to the current develop? It would be nice if it gets included in **1.8.0**.

**Comment by Chocobozzz** [comment]
Sorry for the late. Can I add bluebird as dependency to use [the map function](http://bluebirdjs.com/docs/api/promise.map.html)?

**Comment by Chocobozzz** [comment]
ping @muxator

**Comment by muxator** [comment]
Hi, @Chocobozzz, sorry for being late.

I just tested installing it and bluebird has no dependencies and is not too big (~700 KB).
May there any way of accomplishing what you need just using the standard library?
If not, please go on adding it.

```
~/test$ npm install bluebird
+ bluebird@3.7.2
added 1 package from 1 contributor in 0.247s
```

```
~/test/node_modules$ du -sch bluebird/
712K    bluebird/
712K    total
```

**Comment by raybellis** [comment]
IMHO, adding Bluebird is excessive just to get access to a Promise `.map` function.   In the new async code there are plenty of instances where I've used trivial "native" code to implement similar functionality.

**Comment by Chocobozzz** [comment]
> IMHO, adding Bluebird is excessive just to get access to a Promise .map function. In the new async code there are plenty of instances where I've used trivial "native" code to implement similar functionality.

Where do you use a map with a concurrency limit?

**Comment by raybellis** [comment]
Fair enough, although you didn't call that out as a specific requirement in your suggestion.

**Comment by muxator** [comment]
Before merging this PR, we have to remember that we depend on a new release of ueberdb (that incorporates https://github.com/Pita/ueberDB/pull/118), or we have to go on with #3675.

**Comment by Chocobozzz** [comment]
I created a custom function and updated the PR

**Comment by JohnMcLear** [comment]
FWIW the UeberDB patch got merged ages ago and it's released on npm so should be good from UeberDB side.  cc @muxator

**Comment by muxator** [comment]
This will be pulled in as soon as #3734 is integrated.

**Comment by muxator** [comment]
We can go on with this PR, since ueberDB was updated via #3734.

But I see there are conflicts.

If the conflicts are trivial I can take care of it. If they end up being more that pure dumb text manipulation I will need support from @Chocobozzz.

**Comment by muxator** [comment]
@Chocobozzz: before merging, I would like - please - that you insert a short note explaining the purpose of `src/node/utils/promises.js` for the posterity.


I think I got the reason for the conflicts: your `develop` branch still points to 49449453c9b2. There are no particular conflict otherwise. I can take care of that if updating your repo is complicated.

Just write me a bit of documentation. :smile:

**Comment by Chocobozzz** [comment]
Done :+1:

**Comment by muxator** [comment]
This was long overdue.

Merged & queued for **1.8.3**, thanks.

**Pull request merged**
