### PR TITLE
Live plugin manager

### PR DESCRIPTION
**Pull request by Gared**
Add live-plugin-manager npm package to prevent usage of npm in our project and handling of npm plugin packages

### CODE REVIEW

**Comment by SamTV12345** [comment]
I rebased your commits with develop and fixed the Docker build process. The only tests failing are now with plugins.

**Comment by Gared** [comment]
> @Gared Does it install the dependencies of the plugins?

Yes, it installs the plugins, but the server suddenly shuts down (and restarts again?! 🤔)
Logs:
```
...
[2023-11-03T20:04:28.850] [INFO] http - Closing HTTP server...
[2023-11-03T20:04:28.850] [INFO] socket.io - Closing socket.io engine...
[2023-11-03T20:04:28.851] [INFO] socket.io - All socket.io clients have disconnected
[2023-11-03T20:04:28.851] [INFO] http - HTTP server closed
[2023-11-03T20:04:30.668] [INFO] http - HTTP server listening for connections
...
Running tests successfully...
...
[2023-11-03T20:04:34.487] [INFO] server - Exiting...
[2023-11-03T20:04:34.488] [INFO] server - Stopping Etherpad...
[2023-11-03T20:04:34.488] [INFO] http - Closing HTTP server...
[2023-11-03T20:04:34.489] [INFO] socket.io - Closing socket.io engine...
[2023-11-03T20:04:34.489] [INFO] socket.io - All socket.io clients have disconnected
[2023-11-03T20:04:34.491] [INFO] ueberDB - Database closed
[2023-11-03T20:04:34.492] [INFO] http - HTTP server closed
[2023-11-03T20:04:34.498] [INFO] server - Etherpad stopped
[2023-11-03T20:04:34.498] [INFO] server - Waiting for Node.js to exit...
...
```
And after that all tests are failing, because no http server is running.
Can you image why this happens?

**Comment by SamTV12345** [comment]
This line looks also suspicious: 

```Error: 023-11-03T20:04:56.711] [ERROR] settings - Failed to load hook function "/home/runner/work/etherpad-lite/etherpad-lite/src/plugin_packages/ep_readonly_guest:authenticate" for plugin "ep_readonly_guest" part "ep_readonly_guest" hook set "hooks" hook "authenticate": Error: Cannot find module 'cheerio'
```

**Comment by SamTV12345** [comment]
> > @Gared Does it install the dependencies of the plugins?
> 
> Yes, it installs the plugins, but the server suddenly shuts down (and restarts again?! 🤔) Logs:
> 
> ```
> ...
> [2023-11-03T20:04:28.850] [INFO] http - Closing HTTP server...
> [2023-11-03T20:04:28.850] [INFO] socket.io - Closing socket.io engine...
> [2023-11-03T20:04:28.851] [INFO] socket.io - All socket.io clients have disconnected
> [2023-11-03T20:04:28.851] [INFO] http - HTTP server closed
> [2023-11-03T20:04:30.668] [INFO] http - HTTP server listening for connections
> ...
> Running tests successfully...
> ...
> [2023-11-03T20:04:34.487] [INFO] server - Exiting...
> [2023-11-03T20:04:34.488] [INFO] server - Stopping Etherpad...
> [2023-11-03T20:04:34.488] [INFO] http - Closing HTTP server...
> [2023-11-03T20:04:34.489] [INFO] socket.io - Closing socket.io engine...
> [2023-11-03T20:04:34.489] [INFO] socket.io - All socket.io clients have disconnected
> [2023-11-03T20:04:34.491] [INFO] ueberDB - Database closed
> [2023-11-03T20:04:34.492] [INFO] http - HTTP server closed
> [2023-11-03T20:04:34.498] [INFO] server - Etherpad stopped
> [2023-11-03T20:04:34.498] [INFO] server - Waiting for Node.js to exit...
> ...
> ```
> 
> And after that all tests are failing, because no http server is running. Can you image why this happens?

I just noticed that I can crash the server if the installed_plugins file is blank. Where did you find these logs?

**Comment by Gared** [comment]
> > > @Gared Does it install the dependencies of the plugins?
> > 
> > 
> > Yes, it installs the plugins, but the server suddenly shuts down (and restarts again?! 🤔) Logs:
> > ```
> > ...
> > [2023-11-03T20:04:28.850] [INFO] http - Closing HTTP server...
> > [2023-11-03T20:04:28.850] [INFO] socket.io - Closing socket.io engine...
> > [2023-11-03T20:04:28.851] [INFO] socket.io - All socket.io clients have disconnected
> > [2023-11-03T20:04:28.851] [INFO] http - HTTP server closed
> > [2023-11-03T20:04:30.668] [INFO] http - HTTP server listening for connections
> > ...
> > Running tests successfully...
> > ...
> > [2023-11-03T20:04:34.487] [INFO] server - Exiting...
> > [2023-11-03T20:04:34.488] [INFO] server - Stopping Etherpad...
> > [2023-11-03T20:04:34.488] [INFO] http - Closing HTTP server...
> > [2023-11-03T20:04:34.489] [INFO] socket.io - Closing socket.io engine...
> > [2023-11-03T20:04:34.489] [INFO] socket.io - All socket.io clients have disconnected
> > [2023-11-03T20:04:34.491] [INFO] ueberDB - Database closed
> > [2023-11-03T20:04:34.492] [INFO] http - HTTP server closed
> > [2023-11-03T20:04:34.498] [INFO] server - Etherpad stopped
> > [2023-11-03T20:04:34.498] [INFO] server - Waiting for Node.js to exit...
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And after that all tests are failing, because no http server is running. Can you image why this happens?
> 
> I just noticed that I can crash the server if the installed_plugins file is blank. Where did you find these logs?

The logs of this action here: https://github.com/ether/etherpad-lite/actions/runs/6749637266/job/18350414950
Oh, yes I'm not verifying if the content is valid json...

**Comment by SamTV12345** [comment]
Very interesting. This test run worked https://github.com/ether/etherpad-lite/actions/runs/6776943450/job/18419546669#step:7:1 . So we have a flaky behavior in our tests. I couldn't reproduce that locally.

**Comment by SamTV12345** [comment]
Oh nice. Good job. All tests are green. The most interesting thing is if the frontend admin tests do work consistently now.

**Comment by Gared** [comment]
> Oh nice. Good job. All tests are green. The most interesting thing is if the frontend admin tests do work consistently now.

Yes, I found an error resulting in a restart of the http server resulting in those flaky tests (I guess)

**Comment by SamTV12345** [comment]
That sounds awesome. 👏🏻

**Comment by SamTV12345** [comment]
@Gared Can we merge this so far?

**Comment by Gared** [comment]
@SamTV12345 There is a problem regarding new dependencies that are vulnerable. Can you have a look on it?
Besides that the PR is ready to merge 👍

**Comment by SamTV12345** [comment]
> @SamTV12345 There is a problem regarding new dependencies that are vulnerable. Can you have a look on it? Besides that the PR is ready to merge 👍

Awesome. I'll have a look at it and update the package-lock.json

**Pull request merged**
