### PR TITLE
Fix inconsistencies when deleting content while timeslider is open

### PR DESCRIPTION
**Pull request by JohnMcLear**
It's a simple fix but it had to be nuanced enough to solve it properly.

Bug Ref: #3932

### CODE REVIEW

**Comment by muxator** [comment]
Moving to **1.8.4** since still needs some love.

**Comment by JohnMcLear** [comment]
What love does it need?  Imho this is urgent...

**Comment by muxator** [comment]
Hi,

I moved the issue to **1.8.4** because that was the explicit indication given in the ticket. Until 2 hours ago, the starting comment of this PR https://github.com/ether/etherpad-lite/pull/3934#issue-408695006 read:

> It's a simple fix but it had to be nuanced enough to solve it properly..
>
> **Ugh, don't merge, I just realized it doesn't copy attributes that are set..** <-- this was deleted 2 hours ago
>
> Bug Ref: #3932

I will be glad to merge the PR if it's useful and it's mature.

Please explain clearly what problem it's fixing and what are the remaining drawbacks, if any.

Then we can decide if it's material for **1.8.3** or has to slip to **1.8.4**.

**Comment by JohnMcLear** [comment]
Yea my bad RE that comment I thought I removed it.



What it's fixing.

The problem is that if you are streaming(Play button active) the timeslider and another editor removes all pad attributes (by deleting content) then the logic said "redo the attribute pool from X to Y" but failed if Y was [].  This allows Y to be [] IE the attribute pool to be "empty".  This failing logic caused pad content to be incorrect!  My fix is to allow the attribute pool to be changable from X to [] without erroring.



Drawbacks

I'm not sure, I ran all tests after and tried to replicate other weird edge cases.  It seems the logic only affects timeslider..  I was pretty surgical in the fix going as far deep into the Changeset as I could to ensure I wasn't affecting anything else negatively.  We really need better "collaborative in real time" test coverage I guess to test these Changeset changes.



Thanks!



-----Original message-----

**Comment by muxator** [comment]
Ok, thanks.

I tried to replicate it, but I did not succeed.

What's the way for removing all pad attributes? I've tried removing all the text (CTRL+A, DELETE) while streaming in another window, but I was not able to crash anything.

Is some plugin needed? What's the expected (buggy) outcome? A crash?



**p.s.**: when trying to replicate this issue, I spotted **another** bug in the timeslider: if I delete some text  (for example via backspace), while the play button is running, the deleted text does not disappear from the timeslider window. Worth another issue for a later time, imho.

**Comment by JohnMcLear** [comment]
Afaik that's the bug, if you apply the patch do you still not see the content deleting?  Look in console you should see the error in timeslider when you hit backspace..  *without the patch.  With the patch the pad content should be correct...

**Comment by muxator** [comment]
Confirmed the bug, confirmed the fix.
Scheduling for **1.8.3**, thanks!

**Comment by JohnMcLear** [comment]
You are welcome, and yeah, this is probably my best fix to date for 1.8.3.   Thanks!

**Pull request merged**
