### PR TITLE
lint: Configure ESLint, fix some lint errors

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* lint: Configure ESLint
* lint: Convert CR+LF line endings to LF
* lint: Put opening brace on same line as `function`
* lint: Prevent comments from being interpreted as JSDoc comments
* lint: Run `eslint --fix` on `bin/` and `tests/`
* lint: Run `eslint --fix` on `src/`
* editor: Delete dead code
* editor: Delete commented-out code
* editor: Delete unused `optModFunc` argument
* editor: Delete unused `isTimeUp` argument
* editor: Add argument to suppress SonarCloud error
* tests: Fix what appears to be a typo

### CODE REVIEW

**Comment by rhansen** [comment]
@JohnMcLear I fixed the SonarCloud bugs so this should be ready to go.

**Comment by rhansen** [comment]
Something is broken—frontend tests aren't working. I'll mark this as ready for review once it's fixed.

**Comment by JohnMcLear** [comment]
Is it due to Travis-ci.com restrictions?

**Comment by rhansen** [comment]
I fixed the bug (variables needed to be declared higher up to avoid a ReferenceError) so this is ready for review.

**Comment by JohnMcLear** [comment]
Please resolve conflict

**Pull request merged**
