### PR TITLE
timeslider follow pad contents: only goToLineNumber if it exists

### PR DESCRIPTION
**Pull request by webzwo0i**
fix for https://github.com/ether/etherpad-lite/issues/4389

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Worth building test coverage into this?

**Comment by webzwo0i** [comment]
tests are in and I checked the exception is raised without the fix in this PR. I used the rightstep/leftstep buttons and compared the pad contents, so there is now test coverage for all three timeslider buttons.

**Comment by JohnMcLear** [comment]
https://travis-ci.org/github/ether/etherpad-lite/jobs/733045689#L1796

Fails FF 78 [firefox Windows 7 78.0]     -> FAILED : follows only to lines that exist in the current pad view Error: Timeout of 2

**Comment by webzwo0i** [comment]
Ha! Thanks!
Testing with larger timeout now

**Comment by JohnMcLear** [comment]
@webzwo0i our testing framework can be so annoying :+1:

**Comment by webzwo0i** [comment]
:-D 
I migrated the test to use some of the helper methods I was working on two month ago but did not finish yet and it works (https://travis-ci.org/github/ether/etherpad-lite/jobs/733305037)
https://github.com/ether/etherpad-lite/blob/workaround-dom-latency/tests/frontend/specs/timeslider_follow.js#L32
imo more readable, but the main advantage is that you can use await in a lot of places to avoid setTimeout and problems related to mixing setTimeout and waitFor.

Disadvantage is that it's adding a lot of helper methods, which can be cumbersome to work with. I did this to ensure you don't have to explicitly write waitFor or setTimeouts when using click events, navigation, etc. (Like https://github.com/ether/etherpad-lite/blob/workaround-dom-latency/tests/frontend/helper/methods.js#L85

Probably better to invest time into getting PRs ready for the new frontend helpers than to spend it on try-and-error here :-)

**Comment by JohnMcLear** [comment]
Okay, so do you want to remove the testing stuff/resolve conflicts and I can merge this as a patch then we can add tests later?

**Comment by webzwo0i** [comment]
Yes. You can squash and merge

**Pull request merged**
