### PR TITLE
Ace2Inner: Fix missing spread operator on `args`

### LINKED ISSUE #4885: ep_tables4 started failing withoutany upgrade in the plugin
I had a project which used ep_tables4, and that worked fine, and suddenly it starts failing with the below error

```
[2021-02-28 02:17:15.969] [WARN] client - Uncaught TypeError: Cannot read property '0' of undefined -- {
  errorId: 'GFO1guvRKuzjWlVOf0PS',
  type: 'Uncaught exception',
  msg: "Uncaught TypeError: Cannot read property '0' of undefined",
  url: 'http://192.168.99.100:9001/p/test',
  source: 'http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=dc2a41f2',
  linenumber: 3,
  userAgent: 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36',
  stack: "TypeError: Cannot read property '0' of undefined\n" +
    '    at AttributeManager.setAttributesOnRange (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=dc2a41f2:50:708)\n' +
    '    at Object.Ace2Inner.x.ace_performDocumentApplyAttributesToRange (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=dc2a41f2:3:39309)\n' +
    '    at Object.performDocApplyTblAttrToRow (eval at j (http://192.168.99.100:9001/static/js/require-kernel.js?v=dc2a41f2:10:1408), <anonymous>:5:13234)\n' +
    '    at Object.addTable (eval at j (http://192.168.99.100:9001/static/js/require-kernel.js?v=dc2a41f2:10:1408), <anonymous>:5:6128)\n' +
    '    at Object.doDatatableOptions (eval at j (http://192.168.99.100:9001/static/js/require-kernel.js?v=dc2a41f2:10:1408), <anonymous>:5:4259)\n' +
    '    at Qn (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=dc2a41f2:49:7520)\n' +
    '    at Object.<anonymous> (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=dc2a41f2:49:7948)\n' +
    '    at Object.ace_doDatatableOptions (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=dc2a41f2:49:1023)\n' +
    '    at eval (eval at j (http://192.168.99.100:9001/static/js/require-kernel.js?v=dc2a41f2:10:1408), <anonymous>:5:1609)\n' +
    '    at o (http://192.168.99.100:9001/javascripts/lib/ep_etherpad-lite/static/js/ace2_inner.js?callback=require.define&v=dc2a41f2:3:5925)'
}
```

Here is my docker file:

FROM etherpad/etherpad:1.8.7
RUN bin/installDeps.sh
RUN npm install ep_tables4
EXPOSE 9001
ENTRYPOINT bin/run.sh

**Expected behavior**
The table component should continue to work as it was.

**Screenshots**
image

**Server (please complete the following information):**
 - Etherpad version: latest / stable / 1.8.11
 - OS: Debian GNU/Linux 10 (buster)
 - Node.js version (`node --version`): 14.16.0
 - npm version (`npm --version`):6.14.11

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] : chrome
 - Version [e.g. 22]: 88

**Additional context**
I am aware that is plugin specific, but the plugin was not changed. Any hints will be helpfull as well.

### PR DESCRIPTION
**Pull request by rhansen**
This fixes a bug that was introduced in commit c38c34bef47a74467394797b34165641a87ac620.

Fixes #4885.

### CODE REVIEW

**Comment by rhansen** [comment]
@SubhasishDey Would you please test this PR?

**Comment by JohnMcLear** [comment]
Is there any way we can make a front end test to cover this issue?

**Comment by rhansen** [comment]
Ideally the ep_tables4 maintainers would add some frontend tests to their plugin. I could add some tests to Etherpad, but I think it would take me more time than it is worth.

**Comment by JohnMcLear** [comment]
So the change would only affect the tables plugin and not any other plugins or core functionality?

**Comment by rhansen** [comment]
This PR definitely does not affect core functionality. I don't know if any other plugins are affected. (Only plugins that call `editorInfo.ace_performDocumentApplyAttributesToRange()` are affected.)

**Comment by JohnMcLear** [comment]
Okay will take a look and add some tests to some of our plugins that do.

**Comment by JohnMcLear** [comment]
Just started on test coverage in ep_embedmedia now.  Will land that plugin in test files now.

**Comment by JohnMcLear** [comment]
Tests in and published and merged in to be tested w/ core.

**Comment by SubhasishDey** [comment]
Hi @rhansen 

     I have verified your changes....The plugin ep_tables4 worked fine with your changes.

     Thank you for your quick response.

**Pull request merged**
