### PR TITLE
3408clean hook commit - WIP

### PR DESCRIPTION
**Pull request by JohnMcLear**
Clean PR for the hook from https://github.com/ether/etherpad-lite/pull/3408/files

Note that there are no docs included for this..  

Seperate PRs for other features from that PR inbound.

### CODE REVIEW

**Comment by muxator** [comment]
Thanks John, if possible do the development work in a private repo. I'll have to force push this.

**Comment by JohnMcLear** [comment]
Yea, for now jus tmerge these ones in.  I have to work on ether/ at the moment because I'm doing so much around saucelabs and those tests don't run from johnmclear -- perhaps I could set them up to run from johnmclear after this sprint is over

**Comment by JohnMcLear** [comment]
@muxator assigned to me to recreate on my personal and create PR from there?

**Comment by muxator** [comment]
What's the rationale for this? Reading from #3408 it seems that:

> Added this hook to run custom functions in timeline view

If it is so, this PR should be augmented with documentation (and tests maybe? I do not know if they exists).

The right time for doing it is now, before merging.

**Comment by muxator** [comment]
> @muxator assigned to me to recreate on my personal and create PR from there?

Assigned just for taking note of who did what. It's not important.

The requests for clarifications and for documentation are real (also, if this PR completely replaces #3408 or is if just a part of it).

Thanks

**Comment by JohnMcLear** [comment]
Yea whoops, need to remember how to do docs...

**Comment by muxator** [comment]
Replaced by #3757

**Pull request closed without merging**
