### PR TITLE
Use worker threads to minify JS/CSS files

### PR DESCRIPTION
**Pull request by Chocobozzz**
This is just a proposal

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Stupid question but afaik I have a PR in to update uglify dep, will this conflict?  If so, that's fine, just wanna make sure you are cool with that and aware of it? :)

**Comment by Chocobozzz** [comment]
>  will this conflict?

Yep, but no problem I can rebase :)

**Comment by JohnMcLear** [comment]
@Chocobozzz ready for that rebase buddy :)

**Comment by Chocobozzz** [comment]
Done :+1:

**Comment by muxator** [comment]
We'll integrate this after **1.8.3**.

**Comment by JohnMcLear** [comment]
This isn't working for me, it requires a rebase, I did some work on it but the pages aren't loading.  will look into this further.  @Chocobozzz can you find time to rebase?

**Comment by Chocobozzz** [comment]
Done

**Pull request merged**
