### PR TITLE
Fix: favicon setting issues, external custom favicon is not respected…

### PR DESCRIPTION
**Pull request by KSSaiTeja**
… on /admin pages

the favicon is fixed (path fixed)

fixes: #3392

### CODE REVIEW

**Comment by KSSaiTeja** [comment]
please tell me if it was ok or not, if not please tell me how can i reproduce the issue and how to fix it. As i am a newbie to opensource i am a bit confused to change things in code.
Hope you understand and help me out

**Comment by SamTV12345** [comment]
Hi thanks for the pull request. 

Unfortunately this does not fix this error. ${FAVICON:null} means that if there is no favicon take null which does not show a favicon. The favicon can be configured like you did it through the settings.json. The problem is that when visiting the admin panel the favicon is not shown. So to test this you need to go to http(s)://your-etherpad.instance.com/admin and check if the favicon is there. 

So I think something in the code needs to be changed. The settings.json is the source where the administrator can change settings of etherpad.

But thanks for your try. Feel free to continue your pull request.

**Comment by KSSaiTeja** [comment]
thanks for the reply and suggestion. i will work on the issue you mentioned. I will start fixing it right now

**Comment by KSSaiTeja** [comment]
i’ll let you know with the new commit

**Comment by KSSaiTeja** [comment]
Right now i am checking the settings.json file unfortunately i cant figure the issue.. can you please tell me which lines of code are the cause of this issue. and mention the file names as links.. dont take it as dumb request, as i am beginner, it would be more helpful to me to find the issue by your help and start working out

please understand and try to give the code lines to work on... :D

**Comment by SamTV12345** [comment]
I just had a look it is fixed. If I change the favicon it is also changed on the admin menu.

**Comment by KSSaiTeja** [comment]
i will close the pull request then, thanks for confirming

**Pull request closed without merging**
