### PR TITLE
add Pad.spliceText()

### PR DESCRIPTION
**Pull request by doj**
- add a new function Pad.spliceText() which allows to append a splice to the
  Pad's database.

- refactor Pad.setText() to use the new Pad.spliceText() function

- refactor Pad.appendText() to use the new Pad.spliceText() function

### CODE REVIEW

**Comment by doj** [comment]
I am writing an etherpad plugin https://github.com/doj/ep_codingdojo which requires this new spliceText() function.

**Comment by rhansen** [comment]
While reviewing this PR I noticed some issues in related code (PRs #5326 and #5328). Once PR #5328 is reviewed and merged, would you rebase your PR onto the latest `develop`?

**Comment by doj** [comment]
sure, I'll do that.

**Comment by rhansen** [comment]
#5328 has been merged.

**Comment by rhansen** [comment]
I rebased onto latest `develop`; please review it.

I also pushed some fixes/improvements in a separate fixup commit that I will squash with yours if OK with you.

**Comment by doj** [comment]
I like your changes with better error checking. I "approve" to merge them.

**Pull request merged**
