### PR TITLE
setEmbedLinks: fix the wrong URL when we use etherpad without /p/ in the URL

### PR DESCRIPTION
**Pull request by alekso87**
This solution fixes the problem #3883.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Should be fine, uses ``.val``, can't see any obvious XSS related issues.  Does it gracefully handle any parameters that have been passed IE ``?showChat=false``

**Comment by muxator** [comment]
@alekso87, I have cleaned the history for you, otherwise this PR could not be merged.

Could you have a look at the resulting change and confirm if everything is there? I may have made a mistake.

**Comment by alekso87** [comment]
@muxator Thanks! All are ok.

**Comment by alekso87** [comment]
@JohnMcLear @muxator Can i close current PR and open a new from another branch? I again added an unnecessary commit :( I needed to do PR from the branch, not develop. Sorry

**Comment by muxator** [comment]
> Can i close current PR and open a new from another branch?

Sure. Before starting, pull from the main Etherpad repo, switch to `develop` and create your new branch from there.

**Pull request closed without merging**
