### PR TITLE
import/export: Kill soffice spawned process after 120 seconds

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by rhansen** [comment]
What bug is this fixing?

**Comment by JohnMcLear** [comment]
I emailed you a private file which can hang/crash libreoffice.  Because it makes libreoffice hang you have to kill it.  This kills the bad process.

**Comment by rhansen** [comment]
Ah, gotcha. Given that it is unusual for OpenOffice to hang, perhaps increase the timeout? Maybe 120 seconds? We don't want the timeout to fire just because it's a large document.

**Comment by JohnMcLear** [comment]
> 
> 
> Ah, gotcha. Given that it is unusual for OpenOffice to hang, perhaps increase the timeout? Maybe 120 seconds? We don't want the timeout to fire just because it's a large document.

changed to 120 👍

**Pull request merged**
