### PR TITLE
bump some deps that have warnings from deps

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
We could probably go through and bump a load more stuff too :)

**Comment by Gared** [comment]
@JohnMcLear You mean like here? https://github.com/ether/etherpad-lite/pull/2957

**Comment by JohnMcLear** [comment]
Yea like that but with new bumps :)

**Comment by JohnMcLear** [comment]
don't merge this btw, something is broken with ueberdb2 @ 0.3.5...

**Pull request closed without merging**
