### PR TITLE
check for io.js

### PR DESCRIPTION
**Pull request by nemetz**
Added a check for io.js

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Tnx

**Comment by Gared** [comment]
I think this check is very bad...
The bin/run.sh script also throws a exception that iojs command could not be found.
We should handle the node and iojs executable the same way.

**Comment by JohnMcLear** [comment]
+! @Gared 

@nemetz please put forward a better fix that doesn't throw up an error...

**Comment by JohnMcLear** [comment]
@nemetz are you going to get this done?

**Pull request merged**
