### PR TITLE
import/export: Improve error handling, promisify

### PR DESCRIPTION
**Pull request by rhansen**
Multiple commits:
* tests: Increase import/export test timeouts
* tests: Promisify import/export tests
* tests: Use `assert` to simplify import/export tests
* import/export: Delete unnecessary comments
* Abiword: Reset stdout buffer when starting abiword
* ExportHandler: Replace unnecessary exception with `return`
* import/export: Use Error objects for errors, not strings
* ExportHandler: Pass the error unmodified
* import/export: Spelling fix: "convertor" -> "converter"
* import/export: On export error return 500 instead of crashing
* Abiword: Don't call the callback if null
* Abiword: Reduce log spam
* Abiword: Fix logging of conversion failure
* Abiword: Use the async-provided callback to signal errors
* LibreOffice: Add missing `fileExtension` property on intermediate step
* LibreOffice: Use consistent intermediate filename
* LibreOffice: Use `async.series` to properly handle conversion errors
* LibreOffice: Use the async-provided callback to signal errors
* import/export: Promisify Abiword and LibreOffice conversion
* LibreOffice: Log conversion errors

### CODE REVIEW

**Comment by JohnMcLear** [comment]
can we please modify the timeouts, not entirely remove them?  I don't mind if they are longer but they are present for a purpose :)

**Comment by rhansen** [comment]
Mocha has a default timeout so it won't hang or anything. I prefer to leave out timeouts unless there's a reason to change the default because they're hard to tune and make tests flaky.

**Comment by JohnMcLear** [comment]
The test timeouts are for detecting if a change in an implementation slows down the functionality.

**Comment by rhansen** [comment]
It's better to have purpose-built benchmarks for testing slowdows. Using timeouts for this purpose isn't particularly helpful because the tests will fail on slow machines even if the change did not slow things down, and the tests will pass on fast machines even if the change did slow things down.

**Comment by JohnMcLear** [comment]
> It's better to have purpose-built benchmarks for testing slowdows. Using timeouts for this purpose isn't particularly helpful because the tests will fail on slow machines even if the change did not slow things down, and the tests will pass on fast machines even if the change did slow things down.

While that may be the case can we please not make it part of the conversation of this PR to keep things simple and inline with the rest of the testing specs?

**Comment by rhansen** [comment]
Bumped the timeout to 1s.

**Comment by rhansen** [comment]
This is ready for review @JohnMcLear.

**Pull request merged**
