### PR TITLE
Fixes #1870

### LINKED ISSUE #1870: http API : get saved revisions count
There is [getRevisionsCount](http://etherpad.org/doc/v1.2.7/#index_getrevisionscount_padid) but no way to get saved revisions count.

### PR DESCRIPTION
**Pull request by ldidry**
Add two functions to API :
 * getSavedRevisionsCount
 * listSavedRevisions

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Awesome thanks @ldidry can you please include backend tests with this PR?  Bump me if you need hlep writing them.  They are suppperrrr easy to write though :)  J

**Comment by ldidry** [comment]
I'll try.

**Comment by ldidry** [comment]
I got a problem. It's up to you to say if I have to fix it : we can't save revisions through API right now. So if I want to test if the saved revisions count and list vary, I have to add a `saveRevision(padID, [rev])` API function. It's pretty easy and I can do that, except for one parameter of `addSavedRevision` : savedById. I think it's not ok to add an empty parameter or a random string.

Would it be ok for you if I create an author "API" before saving the revision and use it? Or should I just stay with one test for my methods?

**Comment by ldidry** [comment]
I didn't wait for your answer, I create a saveRevision API function

**Comment by ldidry** [comment]
ping @JohnMcLear

**Comment by JohnMcLear** [comment]
Excellent work thanks!

**Comment by JohnMcLear** [comment]
btw your tests fail

```
 1) getSavedRevisionsCount gets saved revisions count of Pad:
     Error: Unable to get Saved Revisions Count
      at /home/jose/etherpad-lite/tests/backend/specs/api/pad.js:121:37
      at Test.assert (/home/jose/etherpad-lite/src/node_modules/supertest/lib/test.js:213:13)
      at assert (/home/jose/etherpad-lite/src/node_modules/supertest/lib/test.js:132:12)
      at /home/jose/etherpad-lite/src/node_modules/supertest/lib/test.js:129:5
      at Test.Request.callback (/home/jose/etherpad-lite/src/node_modules/supertest/node_modules/superagent/lib/node/index.js:746:30)
      at Test.<anonymous> (/home/jose/etherpad-lite/src/node_modules/supertest/node_modules/superagent/lib/node/index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/home/jose/etherpad-lite/src/node_modules/supertest/node_modules/superagent/lib/node/index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)
```

**Comment by ldidry** [comment]
It works on my computer. Strange. Did you run the test or is it continuous integration?

**Comment by ldidry** [comment]
I just tested on the develop branch (with my commit merged): it worked.

**Comment by JohnMcLear** [comment]
Hrm, try clear your database..

I tried to run the test using bin/backendTests.sh

**Comment by ldidry** [comment]
```
rm var/dirty.db
 ./bin/safeRun.sh /tmp/t.log
./bin/backendTests.sh
```

All tests passed well.

**Comment by JohnMcLear** [comment]
Msut have been a glitch in the matrix, seems fine now :|

**Pull request merged**
