### PR TITLE
If AltGr is pressed it should not be a command key

### PR DESCRIPTION
**Pull request by JohnMcLear**
I'm not sure this is even still a bug, I need someone to test it who has the correct setup I guess!

Fixes https://github.com/ether/etherpad-lite/issues/2884

To test, create a pad (with this branch active) and press AltGr C, you should see a character, you shouldn't have contents copied to clipboard...

### CODE REVIEW

**Comment by muxator** [comment]
I have tried this patch, but I see no changes wrt `Alt`/`AltGr` + 'c` behaviour. Does it fix for you?

Let's see what users answer to https://github.com/ether/etherpad-lite/issues/2884#issuecomment-604765606, because maybe that bug no longer exists.

**Comment by muxator** [comment]
I am inclined to reject this if there is no benefit. Confirmed?

**Comment by JohnMcLear** [comment]
I'm a pleb Brit so not the right person to validate this as I'm 100% uncultured.  🐙

**Comment by JohnMcLear** [comment]
Closing because we think this was fixed upstream.

**Pull request closed without merging**
