### PR TITLE
Re-implement ace_getAttributeOnSelection

### PR DESCRIPTION
**Pull request by marcelklehr**
This is an implementation of the behavior proposed in #2411

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Doh if selStart = selEnd false is always returned..

**Comment by JohnMcLear** [comment]
a selection can be the caret location so really we should be mindful of the previous character at this point..

**Comment by JohnMcLear** [comment]
The idea behind the above statement is that you know what attributes will be applied to the next character typed.

**Comment by marcelklehr** [comment]
Ahh, so that's why you need this. I'd create a separate method for that, though. Something like ace_getAttribsOnCaret

**Comment by JohnMcLear** [comment]
Thanks! :)

**Pull request merged**
