### PR TITLE
Set author color via createAuthor / createAuthorIfNotExistsFor

### LINKED ISSUE #2179: set author color via createAuthor
It should be possible to set the author color via the http `createAuthor` call.

Thoughts? Yes? No?

### PR DESCRIPTION
**Pull request by luto**
fixes #2179
see Issue for details.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Bump @luto

**Comment by JohnMcLear** [comment]
1.4.12 landed without this in, I still think if you are going to extend with params you need to create a new endpoint or so..

**Comment by JohnMcLear** [comment]
This needs a rewrite.

**Comment by luto** [comment]
haha, yes it does :) however, I haven't touched ep for 6 years.

**Pull request closed without merging**
