### PR TITLE
Fix performance for large pads

### PR DESCRIPTION
**Pull request by seballot**
Refs #4228

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@seballot is an absolute ninja :D  Well done man!

I'm going to merge but things to note:

1) Now seeing a Mac / Safari error: 

```
[safari OS X 10.15 13.1] responsiveness.js

[safari OS X 10.15 13.1]   Responsiveness of Editor

[safari OS X 10.15 13.1]     -> FAILED : Fast response to keypress in pad with large amount of contents Error: Error:

[safari OS X 10.15 13.1]      expected 354 to be below 300 (http://localhost:9001/tests/frontend/lib/expect.js:99)

[safari OS X 10.15 13.1]     (http://localhost:9001/tests/frontend/lib/mocha.js:64)

[safari OS X 10.15 13.1] 
```

Probably due to sketchy test.  But weirdly azlso seeing: 

```
[safari OS X 10.15 13.1] timeslider_numeric_padID.js

[safari OS X 10.15 13.1]   timeslider

[safari OS X 10.15 13.1]     -> FAILED : Makes sure the export URIs are as expected when the padID is numeric Error: 

[safari OS X 10.15 13.1]     Error: expected -1 to not equal -1 (http://localhost:9001/tests/frontend/lib/expect.js:99)

[safari OS X 10.15 13.1]     (http://localhost:9001/tests/frontend/lib/mocha.js:64)
```

and obviously Firefox 52 is still crashing due to responsiveness.js, so I'm gonna run the test again, see if those OSX errors go and then merge.

**Comment by JohnMcLear** [comment]
```
[safari OS X 10.15 13.1] FINISHED - 107 tests passed, 0 tests failed, 20  pending, duration: 7:4
```
Must have been a glitch in the underpants.

Merging!  Thanks @seballot .  @joassouza please confirm you get a better UX now :)

**Review by JohnMcLear — CHANGES_REQUESTED** [review]
I think fastRun.sh was committed by accident @seballot ??  If you can remove I can merge :)

**Comment by seballot** [comment]
Hi ! fastRun was not an accident, but I removed it you prefer so the pull request is only focused on the performance thing

**Comment by joassouza** [comment]
Well done @seballot! I've tested here and works amazingly!
Thanks for your work, I really appreciate that
Merci :)

**Pull request merged**
