### PR TITLE
Improved readibility

### PR DESCRIPTION
**Pull request by lmagniez**
In order to solve the issue of having a good readibility on etherpad-lite, I changed as it was requested the set of user color (I made sure every color have a sufficient brightness), and changed the pad's font-size to 16px. 
Issue's link: [issue](https://github.com/ether/etherpad-lite/issues/3233)

### CODE REVIEW

**Comment by lpagliari** [comment]
Awesome work, @lmagniez !! Thanks a lot for it!

@Dhwty does this PR impact your work, as you've mentioned on the original issue?

I'm still feeling these should be features enabled by props on `settings.json` -- one for the colors, one for the font-size / line-height... @lmagniez could you do that, please? The default style would be 12px / 16px, and the customised one 16px / 21px -- I'm trying to keep the same ratio for both configs here, not sure if this is the best approach. Thoughts?

If we use 16px / 16px, we won't have the spacing between lines, which make reading more comfortable.

### 12px / 16px:
image

### 16px / 16px:
image

### 16px / 21px:
image

**Comment by Dhwty** [comment]
> I'm still feeling these should be features enabled by props on settings.json -- one for the colors, one for the font-size / line-height...

If this change goes into settings.json, rather than being a hard-coded change in font size and colour, it's not going to impact me at all. Thanks for the @.

**Comment by lpagliari** [comment]
we can define on `settings.json.template` that the improved styles would be used, and let other people avoid them if they want. At least we make more people to use the improvements of @lmagniez without they needing to do anything when starting their Etherpad instance for the first time

**Comment by vvalembois** [comment]
Sorry for the late reply, and thank you for your suggestions. We will work on it with @lmagniez and @lisonferez when we will be free.

**Comment by lpagliari** [comment]
Thanks, @vvalembois . This will be an excellent improvement for Etherpad!

**Comment by JohnMcLear** [comment]
I really dislike this PR.  Sorry!

**Comment by slel** [comment]
Thaanks!!

**Comment by JohnMcLear** [comment]
Had a number of complaints about this already...

1. Line height wasn't bumped to match font-size
2. I increased line height this has broken numbering and formatting.

**Comment by rohieb** [comment]
As a short feedback to this PR, I have reverted it and related changes on my local instance for now, since I find 16pt too big to read and I cannot turn the font size back to 12pt otherwise except hard-reverting it. However I found that only on my Hi-DPI laptop, on the desktop it looked fine…

**Comment by muxator** [comment]
This change effectively breaks the alignment in Etherpad 1.6.4+ (see for example #3378).

As the feature seems interesting, maybe we can revert the changes on iframe_editor.css (I have them ready to commit) and open a separate line of work where these parameters would be configurable, as suggested by @lpagliari and others.

**Comment by muxator** [comment]
Reverted back to old appearance with 9daade0b95bb.

We can build a more comprehensive approach in a different line of work.

**Comment by fungi** [comment]
Any chance to get a new release for this sometime soonish? We're trying to stick to released versions in production deployments, but have gotten a number of complaints about the font size and line number misalignment since upgrading to deal with the recent vulnerabilities.

**Comment by muxator** [comment]
Released in [1.6.6](https://github.com/ether/etherpad-lite/releases/tag/1.6.6).

**Pull request closed without merging**
