### PR TITLE
add hooks for index.html template

### PR DESCRIPTION
**Pull request by brunob**
ref #3978

Tested with this branch of our infini plugin and it works :)

https://framagit.org/infini/ep_infini/-/tree/new_hooks

Still have to test the `indexCustomInlineScripts` but it should work also from what i see.

Open to discussion on naming of these new hooks.

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Looks good to me, putting into 1.8.5 as

1) Low hanging
2) Very unlikely to cause problems
3) Not breaking

**Comment by brunob** [comment]
thx @JohnMcLear do you want a separate PR in order to add these new hooks to documentation ?

**Comment by JohnMcLear** [comment]
There is docs for EJS hooks?  I didn't think there was...  That's a lot of docs if there is!

**Comment by brunob** [comment]
Yes, it seem https://etherpad.org/doc/v1.8.4/#index_eejsblock_name (see my precedent PR about it).

**Comment by JohnMcLear** [comment]
Yeah docs pr would be required then

**Pull request merged**
