### PR TITLE
Live plugin viewer

### PR DESCRIPTION
**Pull request by SamTV12345**
@Gared I tried to add the live plugin viewer. Unfortunately there is a big problem: The live plugin viewer installs by default everything without npm. That way the main ep plugin is separate from the rest of the plugins so we would need to add an exception for that name. Otherwise I could also try installing with npm.

### CODE REVIEW

**Comment by Gared** [comment]
I'm not really sure that I fully understood the problem. I'll try to test your branch in the next days :-)

**Comment by SamTV12345** [comment]
> I'm not really sure that I fully understood the problem. I'll try to test your branch in the next days :-)

Thanks that is very much appreciated. I opened another branch feature/plugin-viewer that is based upon develop branch and I could progress a little bit further.

**Comment by Gared** [comment]
> > I'm not really sure that I fully understood the problem. I'll try to test your branch in the next days :-)
> 
> Thanks that is very much appreciated. I opened another branch feature/plugin-viewer that is based upon develop branch and I could progress a little bit further.

I couldn't find your branch. Do you have a link where I can find this branch? 😅

**Comment by SamTV12345** [comment]
> > > I'm not really sure that I fully understood the problem. I'll try to test your branch in the next days :-)
> > 
> > 
> > Thanks that is very much appreciated. I opened another branch feature/plugin-viewer that is based upon develop branch and I could progress a little bit further.
> 
> I couldn't find your branch. Do you have a link where I can find this branch? 😅

Sorry my bad. I forgot to push my changes. It is up now.

**Comment by Gared** [comment]
I built a working version on top of your branch:
https://github.com/Gared/etherpad-lite/pull/new/live-plugin-manager

I'm not sure if this is your problem but for loading the plugins (getPackages) I loaded the list of plugins with manager.list() and merged it with the npm response. This worked for me so far. I also could open the frontend and admin plugins page with the list of plugins.

What do you think? @SamTV12345

**Comment by SamTV12345** [comment]
> I built a working version on top of your branch: https://github.com/Gared/etherpad-lite/pull/new/live-plugin-manager
> 
> I'm not sure if this is your problem but for loading the plugins (getPackages) I loaded the list of plugins with manager.list() and merged it with the npm response. This worked for me so far. I also could open the frontend and admin plugins page with the list of plugins.
> 
> What do you think? @SamTV12345

Thanks for the help @Gared. Looks really good. Can you transform this into a real pull request. There are some test cases failing and some debug statements in the code 😄 . But the general approach works without a problem. We could then merge this pull request and test this change intensively.

**Comment by Gared** [comment]
> > I built a working version on top of your branch: https://github.com/Gared/etherpad-lite/pull/new/live-plugin-manager
> > I'm not sure if this is your problem but for loading the plugins (getPackages) I loaded the list of plugins with manager.list() and merged it with the npm response. This worked for me so far. I also could open the frontend and admin plugins page with the list of plugins.
> > What do you think? @SamTV12345
> 
> Thanks for the help @Gared. Looks really good. Can you transform this into a real pull request. There are some test cases failing and some debug statements in the code 😄 . But the general approach works without a problem. We could then merge this pull request and test this change intensively.
> 
> If that works we could try to make Etherpad compatible with Typescript and ESM.

I added migration for old plugins and created a pull request: https://github.com/ether/etherpad-lite/pull/6018
If this is fine for you I would modify github workflows and the Dockerfile to also work with these changes

**Comment by SamTV12345** [comment]
@Gared Thanks. Looks good to me. Seems like the tests are still failing. But the general approach sounds great👍🏻.

**Pull request closed without merging**
