### PR TITLE
Favicon fix

### LINKED ISSUE #3875: Own icon is not displayed in the pads themselves
Hi everybody!

index page
Screenshot at Apr 17 16-01-19
pads page
Screenshot at Apr 17 16-13-05
credentials.json
```
{
  "favicon": "https://other-site.com/favicon.ico",
  "ip": "127.0.0.1",
  "trustProxy": true
}
```

Cache cleaned, did not help.

### PR DESCRIPTION
**Pull request by JohnMcLear**
Easy low hanging fruit for someone new to Etherpad.  Just an example of some modifications required..  see #3875 for work required.

Fixes #3875.

### CODE REVIEW

**Comment by muxator** [comment]
Moving to next release. Not critical for **1.8.4**.

**Comment by brunob** [comment]
Damn, this one haven't been pushed to 1.8.5 :\ Anyway, this should be reopened...

**Comment by JohnMcLear** [comment]
Yeah sorry we just need test coverage to merge it in.

**Comment by brunob** [comment]
and we still forgot to push this one to latest release, time to merge no ? :p

**Comment by JohnMcLear** [comment]
It needs test coverage first no?

**Comment by brunob** [comment]
At least i'm testing in production at pad.infini.fr since a while :)

**Comment by JohnMcLear** [comment]
@brunob sure but if you read the issue it explains all the edge cases that need supporting :)  I just through this PR together to show a newcomer an example of part of a fix for a low hanging fruit :)

**Comment by brunob** [comment]
FTR, with latest development version this patch does the trick :

```diff
diff --git a/src/node/hooks/express/specialpages.js b/src/node/hooks/express/specialpages.js
index 61471348..2b830a6d 100644
--- a/src/node/hooks/express/specialpages.js
+++ b/src/node/hooks/express/specialpages.js
@@ -83,6 +83,9 @@ exports.expressCreateServer = (hookName, args, cb) => {
         settings.skinName,
         'favicon.ico'
     );
+    if (settings.favicon) {
+      filePath = path.join(settings.root, settings.favicon);
+    }
     res.setHeader('Cache-Control', `public, max-age=${settings.maxAge}`);
     res.sendFile(filePath, (err) => {
       // there is no custom favicon, send the default favicon
```

**Comment by brunob** [comment]
:disappointed:

**Comment by rhansen** [comment]
@brunob I pushed some commits that should fix this. Would you please test it?

**Comment by brunob** [comment]
@rhansen tested with our theme which define a custom favicon and it works well \o/

ref https://framagit.org/infini/ep_infini/-/blob/master/infini.js#L23

**Pull request merged**
