### PR TITLE
Fix typo in `apicalls.js` which prevents from importing `isValidJSONPName`

### PR DESCRIPTION
**Pull request by otetard**

### CODE REVIEW

**Comment by nashe** [comment]
cc @muxator @JohnMcLear ;-)

**Comment by muxator** [comment]
Rebased & merged, thanks.

The problem was introduced in dd7894d3c9389a000d11d3a89962d9fcc9c6c44b.

**Comment by gramakri** [comment]
@muxator thanks! Will there be a new release that has this change? Would be good to have a new release as we need to pull in the previous release's security fixes as well.

**Comment by JohnMcLear** [comment]
@muxator feel free to do another release :)


________________________________

**Comment by muxator** [comment]
Released [v1.6.5](https://github.com/ether/etherpad-lite/releases/tag/1.6.5), which should fix this and other small issues.

**Pull request merged**
