### PR TITLE
Export author color

### PR DESCRIPTION
**Pull request by JohnMcLear**
For #374

### CODE REVIEW

**Comment by JohnMcLear** [comment]
@Gared can you please test and merge this if it passes?

**Comment by dcht00** [comment]
Hi all, is there maybe any status update on this?

**Comment by muxator** [comment]
Hi @dcht00, I am not working on this right now. I do not know if someone else is having a look, but the feature looks interesting for sure.
I would welcome contributions on this.

Some practical details:

The feature was developed right on top of 1.6. The contributor could test & eventually fix that version (5cd781d09fd4).
Afterwards, it could be forward ported to current develop (1.7+) and merged there.

**Comment by JohnMcLear** [comment]
@muxator is there still any interest for this?  Looks like it is a relatively healthy PR despite conflicts.

**Comment by muxator** [comment]
This PR has many conflicts, and probably it will have more once we merge #3786.

Should be reworked.

**Comment by JohnMcLear** [comment]
https://www.npmjs.org/package/ep_export_authors <-- this plugin does it anyway.  Closing as it's not something that needs to be in core.

**Comment by Gared** [comment]
But in my plugin I create random author colors, becauase I can't load the original one from database

**Comment by JohnMcLear** [comment]
Yeah I spent a while on this and noticed most of this code is in core...  Not sure why we don't expose it...  ?

**Comment by Gared** [comment]
I think this would be good to expose in plugins, but as far as I know we can't do it right now, because the hook is not async

**Pull request closed without merging**
