### PR TITLE
Add check for special url characters to createPad API function

### PR DESCRIPTION
**Pull request by Gared**
This will add a check to forbid special url characters (like /, ?, & and #) on the createPad API function.
This is only a small improvement, because it doesn't fix the whole bug reported in #2287
Characters like ':' are sanitized by the function padManager.sanitizePadId in APIHandler.js line 414. We should move this function inside the createPad method so we could give back an error if the sanitizedPadId is not equal with the original padId. Is there any reason why every API call with a padId uses this function?

### CODE REVIEW

**Comment by Gared** [comment]
@JohnMcLear Is there anything I should do here?

**Comment by JohnMcLear** [comment]
I'm happy with it if you are

On 14 Mar 2015 22:48, Stefan <notifications@github.com> wrote:

@JohnMcLear<https://github.com/JohnMcLear> Is there anything I should do here?

**Comment by Gared** [comment]
@marcelklehr What do you think? Are you happy with this kind of validation?

**Comment by JohnMcLear** [comment]
Bump @marcelklehr

**Comment by JohnMcLear** [comment]
@Gared if you want to merge this in just for for it as long as you are happy with maintaining it as it grows =+)

**Comment by Gared** [comment]
Fix #1241

**Pull request merged**
