### PR TITLE
Requirejs

### PR DESCRIPTION
**Pull request by redhog**
I have AMDified lots of code, and it all works. Better to merge often and merge early than have lots of conflicts later...

### CODE REVIEW

**Comment by JohnMcLear** [comment]
I'm gonna be testing this today and creating a checklist of stuff left to do =)

**Comment by redhog** [comment]
ping @JohnMcLear I have merged iframes-must-die into requirejs branch and it all works :)

**Comment by JohnMcLear** [comment]
Niceish but that will break most plugins.  Something I wanted to avoid.  Can we chat about this next week?
----- Reply message -----

**Comment by JohnMcLear** [comment]
How are you set for Wed pm?  I can be free then if you can?
----- Reply message -----

**Comment by JohnMcLear** [comment]
Closing because it's way out of scope for now.

**Pull request closed without merging**
