### PR TITLE
Change screenshot on Readme

### PR DESCRIPTION
**Pull request by seballot**

### CODE REVIEW

**Comment by muxator** [comment]
Delicious, thanks!

I had to do some surgery on the `develop` branch due to recent unwanted changes for the testing infrastructure.

After this change is merged, if possible delete your local copy & your github fork and start over again.

**Comment by seballot** [comment]
Yes I see the git history changing a lot from my git UI ! that's funny :)

**Comment by muxator** [comment]
It's not something I would normally do, but there is a lot of work going on and I do not want to stop the other contributors.

I want to keep the `develop` history clean, because bugs will pop up, and it's important to be able to asses when they did.

Could you please share an advice on what git GUI to use for the other developer's benefit? I do not need it because I already use TortoiseHG, but if the others start seeing the history, this may help everyone.

This meta work is wasting a lot of energy on my side.

**Comment by muxator** [comment]
Done, now we can focus on https://github.com/ether/ether.github.com/issues/30

Thanks!

**Comment by luixxiul** [comment]
@seballot I am following your job here and you're doing! I like the new theme quite well. Keep up the nice job :smile:

**Comment by muxator** [comment]
Indeed. Colibris is a breath of fresh air.

And working on an ancient code base such as Etherpad's, improving it while keeping stability is quite a feat.

The community owes you, @seballot.

**Comment by seballot** [comment]
I'm using gitkraken, which is not open source, but quite convenient and very easy to access... But you seems quite more an expert than me for manipulating git history !
Actually it seems gitkraken cannot follow your last operations, cause it seems from my git UI that developer branch come from nowhere (or so far back in history that I can even see the commit before `tests: fix timeslider revision tests (#3898)`, that's odd !

Yes will do etherpad.org during next week I guess !

Thanks @luixxiul and @muxator for those happy words :)

**Pull request merged**
