### PR TITLE
Update german translation from translatewiki

### LINKED ISSUE #2895: Problem with translation into German
Firefox 44.0; Chomium similar problem
Server: Debian 8.3; Kernal 3.16.0-4-amd64
NodeJS Version: v0.10.29

"Neues Dokument" ≙ "New Pad" 
I'm not sure but @german_people: change "Dokument" to Pad
my pull request: https://github.com/ether/etherpad-lite/pull/2896
image

### PR DESCRIPTION
**Pull request by Gared**
Fixes #2895

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Shouldn't this come from the translatewiki team as per normal?

**Comment by Gared** [comment]
@JohnMcLear I know that they commit changes from translatewiki from time to time, but I don't know when so I manually exported the json file with the translation.

**Comment by JohnMcLear** [comment]
bumping @siebrand

**Comment by Gared** [comment]
In the last commit weren't the actual german translations included https://github.com/ether/etherpad-lite/commit/7dd26bd2500edf56510eeb0784fc3b5d08a41eff

**Comment by siebrand** [comment]
The translation are Probsbly already in... https://github.com/ether/etherpad-lite/commit/04e8b0c184f64332b69e97be173b0a7b9e6a3f86

**Comment by Gared** [comment]
@siebrand You're right.
So everything is already done and I can close this PR.

**Pull request closed without merging**
