### PR TITLE
Better HTML Export rewrite hook allows functions to be passed instead of strings means state is saved between plugins

### PR DESCRIPTION
**Pull request by JohnMcLear**
Fix for https://github.com/ether/etherpad-lite/issues/2486

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Use like this
```
exports.asyncLineHTMLForExport = function (hook, context, cb) {
  var align = _analyzeLine(context.attribLine, context.apool);
  if (align) {
    cb('<div style="width:100%;margin:0 auto;list-style-position:inside;text-align:' + align + '">' + context.lineContent + '</div>');
  }
}
```

**Comment by JohnMcLear** [comment]
@Gared I want to get this in for 1.5.1

**Comment by Gared** [comment]
@JohnMcLear Okay, I'm aware of this PR :-)
Maybe we should mark "getLineHTMLForExport" as deprecated?

**Comment by JohnMcLear** [comment]
I tested this quite a lot and it's working well :)

**Comment by Gared** [comment]
I tried to use this new hook in my plugin: https://github.com/Gared/ep_export_authors
but I still can't use asynchronous calls (like db calls) in this hook, because I have to _return_ the new lineContent in this function. 
It would be better (and more the nodejs-way) if the lineContent would be returned as the callback parameter like this:
```
exports.asyncLineHTMLForExport = function (hook, context, cb) {
  ...
  db.getSub("globalAuthor:" + author, ["colorId"], function(err, result) {
    ...
    cb("newLineContent");
  });
}
```

**Comment by JohnMcLear** [comment]
Okay I will rewrite now

**Comment by lpagliari** [comment]
Hey, guys, any news on this? We might need it to fix ep_font_color export to HTML...

**Pull request merged**
