### PR TITLE
Issue #2948 - disable sauce labs frontend tests until they are working.

### PR DESCRIPTION
**Pull request by rhelmer**

### CODE REVIEW

**Comment by lpagliari** [comment]
Is this a WIP, @rhelmer ?

**Comment by rhelmer** [comment]
Well I was hoping it'd work as-is but apparently doesn't :)

Will investigate.

**Comment by rhelmer** [comment]
Oh, oops. I screwed up a merge, fixing...

**Comment by rhelmer** [comment]
@lpagliari sorry about that! how about now?

**Comment by lpagliari** [comment]
👍

**Pull request merged**
