### PR TITLE
Revert "SessionStore: replace password with PASSWORD_HIDDEN when storing in db"

### PR DESCRIPTION
**Pull request by rhansen**
This reverts commit 53f126082a8b3d094e48b159f0f0bc8a5db4b2f4, which
broke user authentication.

Fixes issue #4016.
Reopens issue #3421.

### CODE REVIEW

**Comment by rhansen** [comment]
@JohnMcLear

**Comment by JohnMcLear** [comment]
Hopefully https://github.com/ether/etherpad-lite/pull/4019 will require this PR defunct, but let's see! :D

**Comment by rhansen** [comment]
My preference would be to merge this then merge PR #4019. Rationale: PR #4019 has a non-zero chance of breaking something. If this PR is not merged and PR #4019 needs to be reverted, then we're back to having broken authentication.

**Comment by muxator** [comment]
> My preference would be to merge this then...

Definitely, thanks.
Let's revert the problematic commit and start over.
I will have a look at the proposed remediation tomorrow.

This time we'll have to be stricter.

**Pull request merged**
