### PR TITLE
Bump uglify to v3 - READY FOR REVIEW/MERGE

### PR DESCRIPTION
**Pull request by JohnMcLear**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
I don't see any change in package.json?

**Comment by muxator** [comment]
@JohnMcLear, I am not at my PC now, but these changes are the same that did not work for me in the previous PR (see my comment #3809 with the error log.

Does it work for you?

**Comment by JohnMcLear** [comment]
pull and test please

**Comment by muxator** [comment]
Tested again on a clean install (latest develop) with this PR applied.

As soon as you visit http://localhost:9001/p/somepad it crashes:
```
[2020-04-04 16:48:13.373] [ERROR] console - TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
    at write_ (_http_outgoing.js:618:11)
    at ServerResponse.write (_http_outgoing.js:586:15)
    at /home/muxator/code/etherpad-lite/src/node/utils/Minify.js:236:15
    at /home/muxator/code/etherpad-lite/src/node/utils/Minify.js:388:7
    at /home/muxator/code/etherpad-lite/src/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```


It's the same error in https://github.com/ether/etherpad-lite/pull/3809#issuecomment-608165362. No surprise, since the code it's the same.

**Comment by JohnMcLear** [comment]
﻿Hrm, do me a favor and remove your ``package-lock.json`` and then do ``bin/run.sh``

I'm not doing anything magical I don't think ;\

**Comment by muxator** [comment]
> Hrm, do me a favor and remove your package-lock.json and then do bin/run.sh

John, I have been doing this for every single PR in this project since forever. :)

**Comment by JohnMcLear** [comment]
Are you using a clean settings.json just changing minify to true?

**Comment by JohnMcLear** [comment]
Never mind I can replicate the crash

**Comment by JohnMcLear** [comment]
Sorry, works now, please review.

**Comment by JohnMcLear** [comment]
Wait, wtf I just f5'd and it's back erroring again, fml.

**Comment by muxator** [comment]
Directly committed the content of this PR as 8987c5d813a45c1961ac39276ea9942df22d31b3, since rebasing was problematic.

Closing this.

**Pull request closed without merging**
