### PR TITLE
Page up / page down behavior rewrite

### PR DESCRIPTION
**Pull request by JohnMcLear**
My WIP fixes for https://github.com/ether/etherpad-lite/issues/4621

- [x] Page down works properly
  - [x] Test coverage
- [x] Single paragraph page up puts char at [0,0]
  - [x] Test coverage
- [x] Single paragraph page down puts char at ``[1, line.length]``;
  - [x] Test coverage
- [x] Page up returns to previous line (last location assuming no other edits performed around area or arrow keys etc pressed)  I think we have a bug here around getVisibleLines logic.
  - [x] Test coverage
- [ ] Support for long lines (character position wrapping)
  - [ ] Test coverage (partially done)
- [x] Maintain X caret offset on page down/up events
  - [x] Test coverage
- [x] Page down works from view instead of rep (if rep is not present in viewport?) 
  - [x] Test coverage (mostly done, might wanna add more coverage).
- [x] Support for Shift page up/down events.
  - [x] Test coverage
- [x] Press and hold page up / page down

### CODE REVIEW

**Comment by webzwo0i** [comment]
I did some tests yesterday before your pushes. Maybe it's already outdated, but here are my observations 

- I increased the zoom level quite a bit and noticed the caret is sometimes placed off by one outside the viewport (bottom and top) (scrollNodeVerticallyIntoView leaves it up to the browser to scroll the line into view, not sure if this is related)
- when I zoomed, the line height is always ~24 pixels. It confused me, but maybe is correct? Using ep_font_size the line height changes.
- we should include coverage in connection with ep_font_size and wrapped lines
- keeping page down/up pressed -> browser is hanging, so there should be a fast path

And the most important: I'm not sure if the viewport coordinates top/bottom are accurate. the bottom was x and the top coordinate of a line was above x, but I saw the background color of that line. Is this intended/some CSS internals re background I don't understand?

**Comment by JohnMcLear** [comment]
Yeah they will be outdated mostly as I did a complete rewrite.

Good point re press and hold.  I totally missed that...

**Comment by JohnMcLear** [comment]
@webzwo0i can we get this finished up and merged please? :)

**Comment by JohnMcLear** [comment]
Bump @webzwo0i

**Pull request closed without merging**
