### PR TITLE
Better delete pad script - ready for review / merge - Scheduled for merge 03/04/2020

### PR DESCRIPTION
**Pull request by JohnMcLear**
Uses API which means it works without stopping / starting the server

Resolves: #3795 and #2899

### CODE REVIEW

**Comment by muxator** [comment]
Pulled in, thanks

**Comment by rasos** [comment]
The new `deletePad.js` script does not work here (etherpad 1.8, MariaDB):

```
node deletePad.js GE_HEG_Gruppe_1
/opt/etherpad-lite/tests/backend/loadSettings.js:4
  var settingsStr = fs.readFileSync(__dirname+"/../../settings.json").toString();
                    ^

ReferenceError: fs is not defined
    at Object.loadSettings (/opt/etherpad-lite/tests/backend/loadSettings.js:4:21)
    at Object.<anonymous> (/opt/etherpad-lite/bin/deletePad.js:7:70)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by JohnMcLear** [comment]
Just needs a require fs

**Comment by rasos** [comment]
Well, in the new script we already have a line with

          const fs = require('fs');

Does `fs.readFileSync()` only work here when a string is the first parameter? See discussion on https://github.com/browserify/brfs/issues/36#issuecomment-60694253

        var apikey = fs.readFileSync(filePath,  {encoding: 'utf-8'});

**Comment by rasos** [comment]
Ah, got it. I added 

     const fs = require('fs');

to `/opt/etherpad-lite/tests/backend/loadSettings.js`

Working now ;-)

**Pull request merged**
