### PR TITLE
.git is not needed in docker image

### PR DESCRIPTION
**Pull request by ratopi**
The current docker images containing the complete .git-Repo.

Therefore I fixed content of .dockerignore

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Looks fine to me.

**Comment by muxator** [comment]
Thanks, @ratopi, no reason to keep the `.git` history, indeed.
I did not catch this because I do not use git in my workflow (mercurial fan).

I was almost merging this change, but then I realized that **Etherpad upon start performs version detection looking at the contents of the `.git` directory**:

https://github.com/ether/etherpad-lite/blob/7a999ee398595429f70df8e7533e82371af3f3a2/src/node/utils/Settings.js#L333-L351

We could get away statically generating a version file inside the container at build time, and hopefully reworking the snipped I linked (I find it ugly).

Would you be willing to try?

**Comment by ratopi** [comment]
Hi @muxator,
I'll try that, but I need some time. ;-)

**Comment by muxator** [comment]
FYI: we are going to release next version soon (~a week).

No worries, this can slide in the next if you do not have time.

**Comment by muxator** [comment]
Moving to **1.8.4**, since I hope we'll release **1.8.3** soon.

@ratopi, drop a line if you need help.

**Comment by ratopi** [comment]
Sorry, for not answering a while.

I tried to completely refactoring the Dockerfile, but not finished yet.

Therefore I made a workaround (removing all unused git-objects): See #3917

**Pull request closed without merging**
