### PR TITLE
CSP: Disable the indexCustomInlineScripts hook

### PR DESCRIPTION
**Pull request by rhansen**
Addresses #4401.

cc @brunob

### CODE REVIEW

**Comment by JohnMcLear** [comment]
I am not opposed to this but we need to look at impact (# of plugins / usage) prior to merging.  It is inevitable though so best we notify devs ASAP.  That's a me job unless you want to do it?

**Comment by JohnMcLear** [comment]
Some changes required.

1. Don't remove hook.
1. issue log warning IF inline JS is detected.  References to other JS files here should be fine too.
1. include some comment in HTML saying don't use inline here!  Also include same warning in hook docs.
1. Promote usage of including JS files IE ``<script src=...`` in this hook.

That way it wont be a breaking change but will gently move people away from doing inline JS.  Win-win

**Comment by rhansen** [comment]
(moving discussion in issue #4401 here)

> but what alternative would we have to modify the index inline script after that?

A future commit will move index's inline script to a `.js` file. Perhaps I should squash that into this so that plugins can start migrating from `indexCustomInlineScripts` to `indexCustomScripts`.

> Okay so why remove it? Just ensure the docs say to people to only reference scripts here

The `indexCustomInlineScripts` EJS block is inside `<script>...</script>`, so users can't do `<script src="..."></script>` with this hook—they would have to use the `indexCustomScripts` hook instead.

If we leave the `<script>` block in `index.html` unchanged, then a CSP that prohibits inline code will break the index page. We could move the existing inline code to a separate `.js` to empty the inline `<script>` block except for the `indexCustomInlineScripts` hook, but that would break plugins that want to replace (not augment) the existing code.

> we need to look at impact (# of plugins / usage) prior to merging

The plugin is new (added in May), which I hope means there aren't many users. Do we have a good way to audit existing uses?

**Comment by rhansen** [comment]
I just had an idea that would allow us to remain backward compatible: Instead of moving `index.html`'s inline script to `static/js/index.js`, I could move it to `template/index.js` and turn it into an EJS template that still has the `indexCustomInlineScripts` block. I would have to set up an Express router for that template, but that's not difficult. What do you think?

**Comment by brunob** [comment]
> A future commit will move index's inline script to a .js file. Perhaps I should squash that into this so that plugins can start migrating from indexCustomInlineScripts to indexCustomScripts.

:+1: 

> The plugin is new (added in May), which I hope means there aren't many users. Do we have a good way to audit existing uses?

:+1: too since this hook became public only after 1.8.5 release 29days ago i may be the only one using it :p

**Comment by JohnMcLear** [comment]
+1.  This is a new hook and an easy one for us to habdle first.  A lot of other inline js is added by plugins that interact with the pad.  This isn't a huge task but it's a good day or so of modifying plugins.

**Comment by rhansen** [comment]
@brunob I sent you a merge request to update your plugin: https://framagit.org/infini/ep_infini/-/merge_requests/1

**Comment by brunob** [comment]
@rhansen woot & thx for that and sorry for the delay, i'll test that asap !

**Comment by rhansen** [comment]
Friendly ping @brunob

**Comment by brunob** [comment]
@rhansen tested and i confirm it works well, thx for that i'll merge the PR from our side on next release.

**Comment by JohnMcLear** [comment]
@rhansen as only this plugin used the hook I am +1 merging this.  Did you want to do any final polish before I hit go?

**Comment by rhansen** [comment]
>  Did you want to do any final polish before I hit go?

Feel free to merge any time.

**Comment by brunob** [comment]
@rhansen ftr your PR on our plugin/theme doesn't work with latest etherpad release, maybe my first test was a fail...

If i had an unbind on original script events, our index.js file override the original script well, see :

```js
$(() => {
  $('#go2Name').unbind('submit');
  $('#button').unbind('click');
});
```

I'll may try to make it with `removeEventListener` instead.

**Pull request merged**
