### PR TITLE
URGENT:   Resolve slow MySQL queries (present in 1.8.3)

### PR DESCRIPTION
**Pull request by JohnMcLear**
This optimizes the select queries.

It fixes issues where large databases are painfully slow with Etherpad.

### CODE REVIEW

**Comment by muxator** [comment]
I have some doubts about the proposed change on ueberDB, let's continue the discussion there:
https://github.com/ether/ueberDB/commit/7762f0096458bcb1ada3ad634d1a43f99a1354f0

**Comment by davidmehren** [comment]
We just manually updated ueberDB to 0.4.6 after our instance (with ~750k rows in the database) became unusable with just around 10 users. It drastically improved the response time, so :+1: for merging this.

**Comment by muxator** [comment]
Ok, let's include this change. I'd also like to include https://github.com/ether/ueberDB/pull/129.

This would mean releasing a new version on npm (**0.4.8** -> **0.4.9**).

I'll close this now and will take care of bumping the dependency on ueberDb when @JohnMcLear publishes ueberDb **0.4.9**.

**Comment by JohnMcLear** [comment]
publishing.

**Comment by muxator** [comment]
Replaced by #3975.

**Pull request closed without merging**
