### PR TITLE
updating mocha and refactoring the custom html reporter using events

### LINKED ISSUE #3434: frontend tests: stale mocha.js version
File `tests/frontend/lib/mocha.js` is quite old: first committed in 2012 with ba4ebbba3ba6, slightly modified the day after in 7aee98bce82e ("made test helpers more cross browser compatible").

```diff
-    var query = Mocha.utils.parseQuery(window.location.search || '');
-    if (query.grep) mocha.grep(query.grep);
+    //var query = Mocha.utils.parseQuery(window.location.search || '');
+    //if (query.grep) mocha.grep(query.grep);
 ```

It would be probably useful to update the frontend library like we did for the backend one.

### PR DESCRIPTION
**Pull request by alexanmtz**
A new version of Mocha 7.1.2 was added, downloaded from Mocha official source, and integrated into the front-end tests infrastructure and running on the Browser.

The current version of Mocha was used with a workaround to extend the HTML reporter to add a custom reporter as a hidden div when runs on the browser.

To update this version I had to remove this custom runner `WebdriverAndHtmlReporter`, used to generate a text output in a hidden div to be generated by Mocha events.

Closes #3434

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

pageshot of 'Frontend tests' @ 2020-05-22-2314'02

### CODE REVIEW

**Comment by alexanmtz** [comment]
https://travis-ci.org/github/alexanmtz/etherpad-lite/jobs/693804195

**Comment by JohnMcLear** [comment]
Should this work with Travis?

**Comment by alexanmtz** [comment]
Yes @JohnMcLear

**Comment by JohnMcLear** [comment]
Awesome thanks!

**Comment by webzwo0i** [comment]
@alexanmtz 
I tried to update (because I wanted to use rootHooks that are available in 7.2.0+) but did not succeed. Can you tell me how you integrated mocha? (Which steps are required to build the version in tests/frontend/lib/mocha.js?)
Thank you!

**Comment by alexanmtz** [comment]
@webzwo0i I just replaced the `mocha.js` with the latest version, so when used in the HTML index file, it should be available, as I used the instance on https://github.com/alexanmtz/etherpad-lite/blob/feature/update-mocha-frontend-tests-runner/tests/frontend/runner.js

**Pull request merged**
