### PR TITLE
WIP:explicitly install the latest version of a plugin, fix for #4536

### PR DESCRIPTION
**Pull request by webzwo0i**

### CODE REVIEW

**Comment by webzwo0i** [comment]
need to test further

**Comment by JohnMcLear** [comment]
fwiw i was able to install latest 0.1.7 to 0.2.1 w/ out this patch somehow ;/

**Comment by webzwo0i** [comment]
are you running npm 7.x? maybe they changed something. For me it will install 0.1.20, when I have 0.1.7 installed

**Comment by JohnMcLear** [comment]
node version is 15.1.0

**Comment by webzwo0i** [comment]
weird. node v15.3.0 and npm 6.14.8, when I manually install version 0.1.7 and update via /admin I always get 0.1.20.

**Comment by JohnMcLear** [comment]
Merging anyway because it shouldn't do any harm

**Pull request merged**
